// --- Material block (UnityShaderConverter) @group(2) ---
struct MaterialUniform {
    hSVOffset: vec4<f32>,
    hSVMul: vec4<f32>,
    srcBlend: f32,
    dstBlend: f32,
    zWrite: f32,
    cull: f32,
    stencilComp: f32,
    stencil: f32,
    stencilOp: f32,
    stencilWriteMask: f32,
    stencilReadMask: f32,
    colorMask: f32,
    _pad0: u32,
    _pad1: u32,
}

@group(2) @binding(0) var<uniform> material: MaterialUniform;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(11) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(9) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
fn UnityObjectToClipPos_0( pos_0 : vec3<f32>) -> vec4<f32>
{
    return ((((((vec4<f32>(pos_0, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityObjectToClipPos_1( pos_1 : vec4<f32>) -> vec4<f32>
{
    return UnityObjectToClipPos_0(pos_1.xyz);
}

fn ComputeGrabScreenPos_0( pos_2 : vec4<f32>) -> vec4<f32>
{
    var _S1 : vec4<f32> = pos_2 * vec4<f32>(0.5f);
    var o_0 : vec4<f32> = _S1;
    var _S2 : vec2<f32> = vec2<f32>(_S1.x, _S1.y * -1.0f) + vec2<f32>(_S1.w);
    o_0.x = _S2.x;
    o_0.y = _S2.y;
    var _S3 : vec2<f32> = pos_2.zw;
    o_0.z = _S3.x;
    o_0.w = _S3.y;
    return o_0;
}

struct v2f_0
{
    @location(0) uv_0 : vec2<f32>,
    @location(1) grabPos_0 : vec4<f32>,
    @builtin(position) pos_3 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) vertex_0 : vec4<f32>,
    @location(4) tangent_0 : vec4<f32>,
    @location(5) normal_0 : vec3<f32>,
    @location(6) texcoord_0 : vec4<f32>,
    @location(1) texcoord1_0 : vec4<f32>,
    @location(2) texcoord2_0 : vec4<f32>,
    @location(3) texcoord3_0 : vec4<f32>,
    @location(7) color_0 : vec4<f16>,
};

@vertex
fn vert( _S4 : vertexInput_0) -> v2f_0
{
    var o_1 : v2f_0;
    var _S5 : vec4<f32> = UnityObjectToClipPos_1(_S4.vertex_0);
    o_1.pos_3 = _S5;
    o_1.uv_0 = _S4.texcoord_0.xy;
    o_1.grabPos_0 = ComputeGrabScreenPos_0(_S5);
    return o_1;
}



enable f16;

@binding(27) @group(0) var _GrabTexture_0 : texture_2d<f32>;

@binding(3) @group(0) var unity_usc_resonite_macro_sampler_0 : sampler;

struct GlobalParams_std140_0
{
    @align(16) unity_Lightmap_HDR_0 : vec4<f16>,
    @align(8) unity_DynamicLightmap_HDR_0 : vec4<f16>,
    @align(16) _HSVOffset_0 : vec4<f32>,
    @align(16) _HSVMul_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> globalParams_0 : GlobalParams_std140_0;
fn rgb_to_hsv_no_clip_0( RGB_0 : vec3<f32>) -> vec3<f32>
{
    var HSV_0 : vec3<f32>;
    var _S1 : f32 = RGB_0.x;
    var _S2 : f32 = RGB_0.y;
    var maxChannel_0 : f32;
    var minChannel_0 : f32;
    if(_S1 > _S2)
    {
        maxChannel_0 = _S1;
        minChannel_0 = _S2;
    }
    else
    {
        maxChannel_0 = _S2;
        minChannel_0 = _S1;
    }
    var _S3 : f32 = RGB_0.z;
    if(_S3 > maxChannel_0)
    {
        maxChannel_0 = _S3;
    }
    if(_S3 < minChannel_0)
    {
        minChannel_0 = _S3;
    }
    var _S4 : vec2<f32> = vec2<f32>(vec2<i32>(i32(0)));
    HSV_0.x = _S4.x;
    HSV_0.y = _S4.y;
    HSV_0[i32(2)] = maxChannel_0;
    var delta_0 : f32 = maxChannel_0 - minChannel_0;
    if(delta_0 != 0.0f)
    {
        HSV_0[i32(1)] = delta_0 / HSV_0.z;
        var delRGB_0 : vec3<f32> = (HSV_0.zzz - RGB_0 + vec3<f32>((3.0f * delta_0))) / vec3<f32>((6.0f * delta_0));
        if(_S1 == (HSV_0.z))
        {
            HSV_0[i32(0)] = delRGB_0.z - delRGB_0.y;
        }
        else
        {
            if(_S2 == (HSV_0.z))
            {
                HSV_0[i32(0)] = 0.3333333432674408f + delRGB_0.x - delRGB_0.z;
            }
            else
            {
                if(_S3 == (HSV_0.z))
                {
                    HSV_0[i32(0)] = 0.66666668653488159f + delRGB_0.y - delRGB_0.x;
                }
            }
        }
    }
    return HSV_0;
}

fn hsv_to_rgb_0( HSV_1 : vec3<f32>) -> vec3<f32>
{
    var var_h_0 : f32 = HSV_1.x * 6.0f;
    var var_i_0 : f32 = floor(var_h_0);
    var _S5 : f32 = HSV_1.z;
    var _S6 : f32 = HSV_1.y;
    var var_1_0 : f32 = _S5 * (1.0f - _S6);
    var _S7 : f32 = var_h_0 - var_i_0;
    var var_2_0 : f32 = _S5 * (1.0f - _S6 * _S7);
    var var_3_0 : f32 = _S5 * (1.0f - _S6 * (1.0f - _S7));
    var RGB_1 : vec3<f32>;
    if(var_i_0 == 0.0f)
    {
        RGB_1 = vec3<f32>(_S5, var_3_0, var_1_0);
    }
    else
    {
        if(var_i_0 == 1.0f)
        {
            RGB_1 = vec3<f32>(var_2_0, _S5, var_1_0);
        }
        else
        {
            if(var_i_0 == 2.0f)
            {
                RGB_1 = vec3<f32>(var_1_0, _S5, var_3_0);
            }
            else
            {
                if(var_i_0 == 3.0f)
                {
                    RGB_1 = vec3<f32>(var_1_0, var_2_0, _S5);
                }
                else
                {
                    if(var_i_0 == 4.0f)
                    {
                        RGB_1 = vec3<f32>(var_3_0, var_1_0, _S5);
                    }
                    else
                    {
                        RGB_1 = vec3<f32>(_S5, var_1_0, var_2_0);
                    }
                }
            }
        }
    }
    return RGB_1;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

struct pixelInput_0
{
    @location(0) uv_0 : vec2<f32>,
    @location(1) grabPos_0 : vec4<f32>,
};

@fragment
fn frag( _S8 : pixelInput_0, @builtin(position) pos_0 : vec4<f32>) -> pixelOutput_0
{
    var _S9 : vec4<f16> = vec4<f16>((textureSample((_GrabTexture_0), (unity_usc_resonite_macro_sampler_0), (_S8.grabPos_0.xy / vec2<f32>(_S8.grabPos_0.w)))));
    var c_0 : vec4<f16> = _S9;
    var _S10 : vec3<f32> = rgb_to_hsv_no_clip_0(vec3<f32>(_S9.xyz)) * globalParams_0._HSVMul_0.xyz + globalParams_0._HSVOffset_0.xyz;
    var hsv_0 : vec3<f32> = _S10;
    hsv_0[i32(0)] = fract(_S10.x);
    hsv_0[i32(1)] = saturate(hsv_0.y);
    var _S11 : vec3<f16> = vec3<f16>(hsv_to_rgb_0(hsv_0));
    c_0.x = _S11.x;
    c_0.y = _S11.y;
    c_0.z = _S11.z;
    var _S12 : pixelOutput_0 = pixelOutput_0( c_0 );
    return _S12;
}

