// --- Material block (UnityShaderConverter) @group(2) ---
struct MaterialUniform {
    iterations: f32,
    _pad0: u32,
    _pad1: u32,
    _pad2: u32,
    spread: vec4<f32>,
    refractionStrength: f32,
    depthDivisor: f32,
    srcBlend: f32,
    dstBlend: f32,
    zWrite: f32,
    cull: f32,
    stencilComp: f32,
    stencil: f32,
    stencilOp: f32,
    stencilWriteMask: f32,
    stencilReadMask: f32,
    colorMask: f32,
}

@group(2) @binding(0) var<uniform> material: MaterialUniform;
@group(2) @binding(1) var spreadTex: texture_2d<f32>;
@group(2) @binding(2) var spreadTex_sampler: sampler;
@group(2) @binding(3) var normalMap: texture_2d<f32>;
@group(2) @binding(4) var normalMap_sampler: sampler;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(11) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(9) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
fn UnityObjectToClipPos_0( pos_0 : vec3<f32>) -> vec4<f32>
{
    return ((((((vec4<f32>(pos_0, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityObjectToClipPos_1( pos_1 : vec4<f32>) -> vec4<f32>
{
    return UnityObjectToClipPos_0(pos_1.xyz);
}

fn ComputeGrabScreenPos_0( pos_2 : vec4<f32>) -> vec4<f32>
{
    var _S1 : vec4<f32> = pos_2 * vec4<f32>(0.5f);
    var o_0 : vec4<f32> = _S1;
    var _S2 : vec2<f32> = vec2<f32>(_S1.x, _S1.y * -1.0f) + vec2<f32>(_S1.w);
    o_0.x = _S2.x;
    o_0.y = _S2.y;
    var _S3 : vec2<f32> = pos_2.zw;
    o_0.z = _S3.x;
    o_0.w = _S3.y;
    return o_0;
}

fn UnityObjectToViewPos_0( pos_3 : vec3<f32>) -> vec3<f32>
{
    return ((((((vec4<f32>(pos_3, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(3)])))).xyz;
}

fn UnityObjectToViewPos_1( pos_4 : vec4<f32>) -> vec3<f32>
{
    return UnityObjectToViewPos_0(pos_4.xyz);
}

struct v2f_0
{
    @location(0) uv_0 : vec2<f32>,
    @location(1) grabPos_0 : vec4<f32>,
    @builtin(position) pos_5 : vec4<f32>,
    @location(2) depth_0 : f32,
};

struct vertexInput_0
{
    @location(0) vertex_0 : vec4<f32>,
    @location(4) tangent_0 : vec4<f32>,
    @location(5) normal_0 : vec3<f32>,
    @location(6) texcoord_0 : vec4<f32>,
    @location(1) texcoord1_0 : vec4<f32>,
    @location(2) texcoord2_0 : vec4<f32>,
    @location(3) texcoord3_0 : vec4<f32>,
    @location(7) color_0 : vec4<f16>,
};

@vertex
fn vert( _S4 : vertexInput_0) -> v2f_0
{
    var o_1 : v2f_0;
    var _S5 : vec4<f32> = UnityObjectToClipPos_1(_S4.vertex_0);
    o_1.pos_5 = _S5;
    o_1.uv_0 = _S4.texcoord_0.xy;
    o_1.grabPos_0 = ComputeGrabScreenPos_0(_S5);
    o_1.depth_0 = - UnityObjectToViewPos_1(_S4.vertex_0).z;
    return o_1;
}



enable f16;

@binding(28) @group(0) var _CameraDepthTexture_0 : texture_2d<f32>;

@binding(3) @group(0) var unity_usc_resonite_macro_sampler_0 : sampler;

struct SLANG_ParameterGroup_UnityPerCamera_std140_0
{
    @align(16) _Time_0 : vec4<f32>,
    @align(16) U_SinTime_0 : vec4<f32>,
    @align(16) _CosTime_0 : vec4<f32>,
    @align(16) unity_DeltaTime_0 : vec4<f32>,
    @align(16) _WorldSpaceCameraPos_0 : vec3<f32>,
    @align(16) _ProjectionParams_0 : vec4<f32>,
    @align(16) U_ScreenParams_0 : vec4<f32>,
    @align(16) _ZBufferParams_0 : vec4<f32>,
    @align(16) unity_OrthoParams_0 : vec4<f32>,
};

@binding(4) @group(0) var<uniform> UnityPerCamera_0 : SLANG_ParameterGroup_UnityPerCamera_std140_0;
@binding(30) @group(0) var _GrabTexture_0 : texture_2d<f32>;

struct GlobalParams_std140_0
{
    @align(16) unity_Lightmap_HDR_0 : vec4<f16>,
    @align(8) unity_DynamicLightmap_HDR_0 : vec4<f16>,
    @align(16) _GammaCurve_0 : f32,
    @align(4) _DepthDivisor_0 : f32,
    @align(8) U_Spread_0 : vec2<f32>,
    @align(16) _Iterations_0 : f32,
};

@binding(0) @group(0) var<uniform> globalParams_0 : GlobalParams_std140_0;
fn LinearEyeDepth_0( z_0 : f32) -> f32
{
    return 1.0f / (UnityPerCamera_0._ZBufferParams_0.z * z_0 + UnityPerCamera_0._ZBufferParams_0.w);
}

fn evrDepthFade_0( screenUv_0 : vec2<f32>,  vertexDepth_0 : f32) -> f32
{
    return (LinearEyeDepth_0((textureSample((_CameraDepthTexture_0), (unity_usc_resonite_macro_sampler_0), (screenUv_0))).x) - vertexDepth_0) / globalParams_0._DepthDivisor_0;
}

fn evrCalculateBlur_0( screenUv_1 : vec2<f32>,  uv_0 : vec2<f32>,  depth_0 : f32,  iterations_0 : f32) -> vec4<f16>
{
    const _S1 : vec4<f16> = vec4<f16>(0.0h, 0.0h, 0.0h, 0.0h);
    var _S2 : f16 = f16(6.28318548202514648f / iterations_0);
    var spread_0 : vec2<f32> = globalParams_0.U_Spread_0 * vec2<f32>(saturate(evrDepthFade_0(screenUv_1, depth_0)));
    var n_0 : i32 = i32(0);
    var c_0 : vec4<f16> = _S1;
    for(;;)
    {
        if(f32(n_0) < iterations_0)
        {
        }
        else
        {
            break;
        }
        var angle_0 : f32 = f32(_S2 * f16(n_0));
        var c_1 : vec4<f16> = c_0 + vec4<f16>((textureSample((_GrabTexture_0), (unity_usc_resonite_macro_sampler_0), (screenUv_1 + vec2<f32>(- cos(angle_0), sin(angle_0)) * spread_0))));
        n_0 = n_0 + i32(1);
        c_0 = c_1;
    }
    return vec4<f16>(vec4<f32>(c_0) / vec4<f32>(iterations_0));
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

struct pixelInput_0
{
    @location(0) uv_1 : vec2<f32>,
    @location(1) grabPos_0 : vec4<f32>,
    @location(2) depth_1 : f32,
};

@fragment
fn frag( _S3 : pixelInput_0, @builtin(position) pos_0 : vec4<f32>) -> pixelOutput_0
{
    var _S4 : pixelOutput_0 = pixelOutput_0( evrCalculateBlur_0(_S3.grabPos_0.xy / vec2<f32>(_S3.grabPos_0.w), _S3.uv_1, _S3.depth_1, globalParams_0._Iterations_0) );
    return _S4;
}

