// --- Material block (UnityShaderConverter) @group(1) ---
struct MaterialUniform {
    color: vec4<f32>,
    cutoff: f32,
    glossiness: f32,
    glossMapScale: f32,
    smoothnessTextureChannel: f32,
    metallic: f32,
    specularHighlights: f32,
    glossyReflections: f32,
    bumpScale: f32,
    parallax: f32,
    occlusionStrength: f32,
    _pad0: u32,
    _pad1: u32,
    emissionColor: vec4<f32>,
    detailNormalMapScale: f32,
    uVSec: f32,
    mode: f32,
    srcBlend: f32,
    dstBlend: f32,
    zWrite: f32,
    offsetFactor: f32,
    offsetUnits: f32,
}

@group(1) @binding(0) var<uniform> material: MaterialUniform;
@group(1) @binding(1) var mainTex: texture_2d<f32>;
@group(1) @binding(2) var mainTex_sampler: sampler;
@group(1) @binding(3) var metallicGlossMap: texture_2d<f32>;
@group(1) @binding(4) var metallicGlossMap_sampler: sampler;
@group(1) @binding(5) var bumpMap: texture_2d<f32>;
@group(1) @binding(6) var bumpMap_sampler: sampler;
@group(1) @binding(7) var parallaxMap: texture_2d<f32>;
@group(1) @binding(8) var parallaxMap_sampler: sampler;
@group(1) @binding(9) var occlusionMap: texture_2d<f32>;
@group(1) @binding(10) var occlusionMap_sampler: sampler;
@group(1) @binding(11) var emissionMap: texture_2d<f32>;
@group(1) @binding(12) var emissionMap_sampler: sampler;
@group(1) @binding(13) var detailMask: texture_2d<f32>;
@group(1) @binding(14) var detailMask_sampler: sampler;
@group(1) @binding(15) var detailAlbedoMap: texture_2d<f32>;
@group(1) @binding(16) var detailAlbedoMap_sampler: sampler;
@group(1) @binding(17) var detailNormalMap: texture_2d<f32>;
@group(1) @binding(18) var detailNormalMap_sampler: sampler;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(7) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
struct _Array_std140_matrixx3Cfloatx2C4x2C4x3E4_0
{
    @align(16) data_1 : array<_MatrixStorage_float4x4_ColMajorstd140_0, i32(4)>,
};

struct SLANG_ParameterGroup_UnityShadows_std140_0
{
    @align(16) unity_ShadowSplitSpheres_0 : array<vec4<f32>, i32(4)>,
    @align(16) unity_ShadowSplitSqRadii_0 : vec4<f32>,
    @align(16) unity_LightShadowBias_0 : vec4<f32>,
    @align(16) _LightSplitsNear_0 : vec4<f32>,
    @align(16) _LightSplitsFar_0 : vec4<f32>,
    @align(16) unity_WorldToShadow_0 : _Array_std140_matrixx3Cfloatx2C4x2C4x3E4_0,
    @align(16) _LightShadowData_0 : vec4<f32>,
    @align(16) unity_ShadowFadeCenterAndType_0 : vec4<f32>,
};

@binding(6) @group(0) var<uniform> UnityShadows_0 : SLANG_ParameterGroup_UnityShadows_std140_0;
struct _Array_std140_vectorx3Chalfx2C4x3E8_0
{
    @align(16) data_2 : array<vec8<f16>, i32(8)>,
};

struct SLANG_ParameterGroup_UnityLighting_std140_0
{
    @align(16) _WorldSpaceLightPos0_0 : vec4<f32>,
    @align(16) _LightPositionRange_0 : vec4<f32>,
    @align(16) _LightProjectionParams_0 : vec4<f32>,
    @align(16) unity_4LightPosX0_0 : vec4<f32>,
    @align(16) unity_4LightPosY0_0 : vec4<f32>,
    @align(16) unity_4LightPosZ0_0 : vec4<f32>,
    @align(16) unity_4LightAtten0_0 : vec4<f16>,
    @align(16) unity_LightColor_0 : _Array_std140_vectorx3Chalfx2C4x3E8_0,
    @align(16) unity_LightPosition_0 : array<vec4<f32>, i32(8)>,
    @align(16) unity_LightAtten_0 : _Array_std140_vectorx3Chalfx2C4x3E8_0,
    @align(16) unity_SpotDirection_0 : array<vec4<f32>, i32(8)>,
    @align(16) unity_SHAr_0 : vec4<f16>,
    @align(8) unity_SHAg_0 : vec4<f16>,
    @align(16) unity_SHAb_0 : vec4<f16>,
    @align(8) unity_SHBr_0 : vec4<f16>,
    @align(16) unity_SHBg_0 : vec4<f16>,
    @align(8) unity_SHBb_0 : vec4<f16>,
    @align(16) unity_SHC_0 : vec4<f16>,
    @align(8) unity_OcclusionMaskSelector_0 : vec4<f16>,
    @align(16) unity_ProbesOcclusion_0 : vec4<f16>,
};

@binding(4) @group(0) var<uniform> UnityLighting_0 : SLANG_ParameterGroup_UnityLighting_std140_0;
struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(9) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
fn UnityObjectToWorldNormal_0( norm_0 : vec3<f32>) -> vec3<f32>
{
    var _S1 : mat4x4<f32> = mat4x4<f32>(UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(3)]);
    return normalize((((mat3x3<f32>(_S1[i32(0)].xyz, _S1[i32(1)].xyz, _S1[i32(2)].xyz)) * (norm_0))));
}

fn UnityWorldSpaceLightDir_0( worldPos_0 : vec3<f32>) -> vec3<f32>
{
    return UnityLighting_0._WorldSpaceLightPos0_0.xyz - worldPos_0 * vec3<f32>(UnityLighting_0._WorldSpaceLightPos0_0.w);
}

fn UnityClipSpaceShadowCasterPos_0( vertex_0 : vec4<f32>,  normal_0 : vec3<f32>) -> vec4<f32>
{
    var wPos_0 : vec4<f32> = (((vertex_0) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))));
    if((UnityShadows_0.unity_LightShadowBias_0.z) != 0.0f)
    {
        var wNormal_0 : vec3<f32> = UnityObjectToWorldNormal_0(normal_0);
        var shadowCos_0 : f32 = dot(wNormal_0, normalize(UnityWorldSpaceLightDir_0(wPos_0.xyz)));
        var _S2 : vec3<f32> = wPos_0.xyz - wNormal_0 * vec3<f32>((UnityShadows_0.unity_LightShadowBias_0.z * sqrt(1.0f - shadowCos_0 * shadowCos_0)));
        wPos_0.x = _S2.x;
        wPos_0.y = _S2.y;
        wPos_0.z = _S2.z;
    }
    return (((wPos_0) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityApplyLinearShadowBias_0( clipPos_0 : vec4<f32>) -> vec4<f32>
{
    var _S3 : vec4<f32> = clipPos_0;
    _S3[i32(2)] = _S3[i32(2)] + max(-1.0f, min(UnityShadows_0.unity_LightShadowBias_0.x / clipPos_0.w, 0.0f));
    _S3[i32(2)] = mix(_S3.z, min(_S3.z, _S3.w), UnityShadows_0.unity_LightShadowBias_0.y);
    return _S3;
}

struct VertexOutput_0
{
    @builtin(position) pos_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) vertex_1 : vec4<f32>,
    @location(1) normal_1 : vec3<f32>,
    @location(2) uv0_0 : vec2<f32>,
};

@vertex
fn vertShadowCaster( _S4 : vertexInput_0) -> VertexOutput_0
{
    var output_0 : VertexOutput_0;
    output_0.pos_0 = UnityApplyLinearShadowBias_0(UnityClipSpaceShadowCasterPos_0(_S4.vertex_1, _S4.normal_1));
    return output_0;
}



enable f16;

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

@fragment
fn fragShadowCaster(@builtin(position) pos_0 : vec4<f32>) -> pixelOutput_0
{
    var _S1 : pixelOutput_0 = pixelOutput_0( vec4<f16>(vec4<i32>(i32(0))) );
    return _S1;
}

