[display]
focused_fps = 242
unfocused_fps = 55

[rendering]
vsync = false
exposure = 0.9800000190734863

[debug]
log_verbose = false
power_preference = "high_performance"
gpu_validation_layers = false
debug_hud_frame_timing = true
debug_hud_enabled = true
debug_hud_transforms = true
