// --- Material block (UnityShaderConverter) @group(2) ---
struct MaterialUniform {
    color: vec4<f32>,
    cutoff: f32,
    srcBlend: f32,
    dstBlend: f32,
    zWrite: f32,
    cull: f32,
    distort: f32,
    zTest: f32,
    _pad0: u32,
}

@group(2) @binding(0) var<uniform> material: MaterialUniform;
@group(2) @binding(1) var reflectionTex: texture_2d<f32>;
@group(2) @binding(2) var reflectionTex_sampler: sampler;
@group(2) @binding(3) var normalMap: texture_2d<f32>;
@group(2) @binding(4) var normalMap_sampler: sampler;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(11) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(9) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
struct SLANG_ParameterGroup_UnityPerCamera_std140_0
{
    @align(16) _Time_0 : vec4<f32>,
    @align(16) U_SinTime_0 : vec4<f32>,
    @align(16) _CosTime_0 : vec4<f32>,
    @align(16) unity_DeltaTime_0 : vec4<f32>,
    @align(16) _WorldSpaceCameraPos_0 : vec3<f32>,
    @align(16) _ProjectionParams_0 : vec4<f32>,
    @align(16) U_ScreenParams_0 : vec4<f32>,
    @align(16) _ZBufferParams_0 : vec4<f32>,
    @align(16) unity_OrthoParams_0 : vec4<f32>,
};

@binding(4) @group(0) var<uniform> UnityPerCamera_0 : SLANG_ParameterGroup_UnityPerCamera_std140_0;
struct GlobalParams_std140_0
{
    @align(16) unity_Lightmap_HDR_0 : vec4<f16>,
    @align(8) unity_DynamicLightmap_HDR_0 : vec4<f16>,
    @align(16) _GammaCurve_0 : f32,
    @align(4) _stereoActiveEye_0 : f32,
};

@binding(0) @group(0) var<uniform> globalParams_0 : GlobalParams_std140_0;
fn UnityObjectToClipPos_0( pos_0 : vec3<f32>) -> vec4<f32>
{
    return ((((((vec4<f32>(pos_0, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityObjectToClipPos_1( pos_1 : vec4<f32>) -> vec4<f32>
{
    return UnityObjectToClipPos_0(pos_1.xyz);
}

fn UnityWorldSpaceViewDir_0( worldPos_0 : vec3<f32>) -> vec3<f32>
{
    return UnityPerCamera_0._WorldSpaceCameraPos_0.xyz - worldPos_0;
}

fn WorldSpaceViewDir_0( localPos_0 : vec4<f32>) -> vec3<f32>
{
    return UnityWorldSpaceViewDir_0((((localPos_0) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)])))).xyz);
}

fn ComputeNonStereoScreenPos_0( pos_2 : vec4<f32>) -> vec4<f32>
{
    var _S1 : vec4<f32> = pos_2 * vec4<f32>(0.5f);
    var o_0 : vec4<f32> = _S1;
    var _S2 : vec2<f32> = vec2<f32>(_S1.x, _S1.y * UnityPerCamera_0._ProjectionParams_0.x) + vec2<f32>(_S1.w);
    o_0.x = _S2.x;
    o_0.y = _S2.y;
    var _S3 : vec2<f32> = pos_2.zw;
    o_0.z = _S3.x;
    o_0.w = _S3.y;
    return o_0;
}

struct v2f_0
{
    @builtin(position) vertex_0 : vec4<f32>,
    @location(0) ref_0 : vec4<f32>,
    @location(1) viewDir_0 : vec3<f32>,
    @location(3) eyeIndex_0 : f32,
};

struct vertexInput_0
{
    @location(0) vertex_1 : vec4<f32>,
    @location(1) normal_0 : vec3<f32>,
};

@vertex
fn vert( _S4 : vertexInput_0) -> v2f_0
{
    var o_1 : v2f_0;
    var _S5 : vec4<f32> = UnityObjectToClipPos_1(_S4.vertex_1);
    o_1.vertex_0 = _S5;
    var _S6 : vec3<f32> = WorldSpaceViewDir_0(_S4.vertex_1);
    o_1.viewDir_0.x = _S6.x;
    o_1.viewDir_0.z = _S6.y;
    o_1.viewDir_0.y = _S6.z;
    o_1.ref_0 = ComputeNonStereoScreenPos_0(_S5);
    o_1.eyeIndex_0 = globalParams_0._stereoActiveEye_0;
    return o_1;
}



enable f16;

@binding(30) @group(0) var _ReflectionTex_0 : texture_2d<f32>;

@binding(3) @group(0) var unity_usc_resonite_macro_sampler_0 : sampler;

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

struct pixelInput_0
{
    @location(0) ref_0 : vec4<f32>,
    @location(1) viewDir_0 : vec3<f32>,
    @location(3) eyeIndex_0 : f32,
};

struct v2f_0
{
     vertex_0 : vec4<f32>,
     ref_1 : vec4<f32>,
     viewDir_1 : vec3<f32>,
     eyeIndex_1 : f32,
};

@fragment
fn frag( _S1 : pixelInput_0, @builtin(position) vertex_1 : vec4<f32>) -> pixelOutput_0
{
    var _S2 : v2f_0;
    _S2.vertex_0 = vertex_1;
    _S2.ref_1 = _S1.ref_0;
    _S2.viewDir_1 = _S1.viewDir_0;
    _S2.eyeIndex_1 = _S1.eyeIndex_0;
    _S2.viewDir_1 = normalize(_S2.viewDir_1);
    var uv_0 : vec4<f32> = _S2.ref_1;
    var _S3 : vec2<f32> = _S2.ref_1.xy / vec2<f32>(_S2.ref_1.w);
    uv_0.x = _S3.x;
    uv_0.y = _S3.y;
    if((_S2.eyeIndex_1) >= 0.0f)
    {
        uv_0[i32(0)] = uv_0[i32(0)] * 0.5f + _S2.eyeIndex_1 * 0.5f;
    }
    var _S4 : pixelOutput_0 = pixelOutput_0( vec4<f16>((textureSample((_ReflectionTex_0), (unity_usc_resonite_macro_sampler_0), (uv_0.xy)))) );
    return _S4;
}

