// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct v2f_0
{
    @builtin(position) vertex_0 : vec4<f16>,
};

@vertex
fn vert() -> v2f_0
{
    var o_0 : v2f_0;
    o_0.vertex_0 = vec4<f16>(0.0h, 0.0h, 0.0h, 0.0h);
    return o_0;
}



enable f16;

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

@fragment
fn frag(@builtin(position) vertex_0 : vec4<f32>) -> pixelOutput_0
{
    discard;
    var _S1 : pixelOutput_0 = pixelOutput_0( vec4<f16>(0.0h, 0.0h, 0.0h, 0.0h) );
    return _S1;
}

