// --- Material block (UnityShaderConverter) @group(2) ---
struct MaterialUniform {
    srcBlend: f32,
    dstBlend: f32,
    zWrite: f32,
    cull: f32,
    zTest: f32,
    _pad0: u32,
    _pad1: u32,
    _pad2: u32,
}

@group(2) @binding(0) var<uniform> material: MaterialUniform;
@group(2) @binding(1) var mainTex: texture_2d<f32>;
@group(2) @binding(2) var mainTex_sampler: sampler;
@group(2) @binding(3) var normalMap: texture_2d<f32>;
@group(2) @binding(4) var normalMap_sampler: sampler;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(11) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(9) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
fn UnityObjectToClipPos_0( pos_0 : vec3<f32>) -> vec4<f32>
{
    return ((((((vec4<f32>(pos_0, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityObjectToClipPos_1( pos_1 : vec4<f32>) -> vec4<f32>
{
    return UnityObjectToClipPos_0(pos_1.xyz);
}

fn UnityObjectToWorldNormal_0( norm_0 : vec3<f32>) -> vec3<f32>
{
    var _S1 : mat4x4<f32> = mat4x4<f32>(UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_WorldToObject_0.data_0[i32(3)][i32(3)]);
    return normalize((((mat3x3<f32>(_S1[i32(0)].xyz, _S1[i32(1)].xyz, _S1[i32(2)].xyz)) * (norm_0))));
}

struct evr_v2f_0
{
    @builtin(position) vertex_0 : vec4<f32>,
    @location(0) normal_0 : vec3<f32>,
    @location(3) position_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) vertex_1 : vec4<f32>,
    @location(1) normal_1 : vec3<f32>,
};

@vertex
fn vert( _S2 : vertexInput_0) -> evr_v2f_0
{
    var o_0 : evr_v2f_0;
    o_0.vertex_0 = UnityObjectToClipPos_1(_S2.vertex_1);
    o_0.position_0 = _S2.vertex_1;
    o_0.normal_0 = UnityObjectToWorldNormal_0(_S2.normal_1);
    return o_0;
}



enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(11) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
@binding(30) @group(0) var _MainTex_0 : texture_2d<f32>;

@binding(3) @group(0) var unity_usc_resonite_macro_sampler_0 : sampler;

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

struct pixelInput_0
{
    @location(0) normal_0 : vec3<f32>,
    @location(3) position_0 : vec4<f32>,
};

struct evr_v2f_0
{
     vertex_0 : vec4<f32>,
     normal_1 : vec3<f32>,
     position_1 : vec4<f32>,
};

@fragment
fn frag( _S1 : pixelInput_0, @builtin(position) vertex_1 : vec4<f32>) -> pixelOutput_0
{
    var _S2 : evr_v2f_0;
    _S2.vertex_0 = vertex_1;
    _S2.normal_1 = _S1.normal_0;
    _S2.position_1 = _S1.position_0;
    var _S3 : mat4x4<f32> = mat4x4<f32>(UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixV_0.data_0[i32(3)][i32(3)]);
    var _S4 : vec3<f32> = (((normalize(_S2.normal_1)) * (mat3x3<f32>(_S3[i32(0)].xyz, _S3[i32(1)].xyz, _S3[i32(2)].xyz))));
    _S2.normal_1 = _S4;
    var _S5 : vec2<f32> = vec2<f32>(0.5f);
    var _S6 : pixelOutput_0 = pixelOutput_0( vec4<f16>((textureSample((_MainTex_0), (unity_usc_resonite_macro_sampler_0), (_S4.xy * _S5 + _S5)))) );
    return _S6;
}

