//! Converted Unity/Resonite shaders live under [`generated`](generated/).
//! Hand-written modules go below the end marker to avoid merge conflicts.
//!
//! Regenerate from the `Renderide/` directory:
//! `dotnet run --project generators/UnityShaderConverter --` (with `slangc` on `PATH` / `SLANGC`), or `--skip-slang` if WGSL is already on disk.

// GENERATED BY UnityShaderConverter — do not edit between this line and the end marker.
pub mod generated;
// --- END UNITY_SHADER_CONVERTER_GENERATED ---

#[cfg(test)]
mod wgsl_validate_tests {
    /// Validates that committed sample WGSL parses with the same `naga` revision `wgpu` uses.
    #[test]
    fn minimal_unlit_sample_wgsl_parses() {
        let src = super::generated::converter_minimal_unlit::material::PASS0_WGSL;
        let mut front = naga::front::wgsl::Frontend::new();
        let _ = front
            .parse(src)
            .expect("sample WGSL should parse; fix the file or regenerate with slangc");
    }
}
