// --- Material block (UnityShaderConverter) @group(2) ---
struct MaterialUniform {
    mainTex_ST: vec4<f32>,
    depthTex_ST: vec4<f32>,
    depthFrom: f32,
    depthTo: f32,
    _pad0: u32,
    _pad1: u32,
    angle: vec4<f32>,
    nearClip: f32,
    farClip: f32,
    discardThreshold: f32,
    discardOffset: f32,
    srcBlend: f32,
    dstBlend: f32,
    zWrite: f32,
    _pad2: u32,
}

@group(2) @binding(0) var<uniform> material: MaterialUniform;
@group(2) @binding(1) var mainTex: texture_2d<f32>;
@group(2) @binding(2) var mainTex_sampler: sampler;
@group(2) @binding(3) var depthTex: texture_2d<f32>;
@group(2) @binding(4) var depthTex_sampler: sampler;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

@binding(29) @group(0) var _DepthTex_0 : texture_2d<f32>;

@binding(3) @group(0) var unity_usc_resonite_macro_sampler_0 : sampler;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(11) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(9) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
struct GlobalParams_std140_0
{
    @align(16) unity_Lightmap_HDR_0 : vec4<f16>,
    @align(8) unity_DynamicLightmap_HDR_0 : vec4<f16>,
    @align(16) _MainTex_ST_0 : vec4<f32>,
    @align(16) _DepthTex_ST_0 : vec4<f32>,
    @align(16) _DepthFrom_0 : f32,
    @align(4) _DepthTo_0 : f32,
    @align(16) _Angle_0 : vec4<f32>,
    @align(16) _NearClip_0 : f32,
    @align(4) _FarClip_0 : f32,
    @align(8) _DiscardThreshold_0 : f32,
    @align(4) _DiscardOffset_0 : f32,
};

@binding(0) @group(0) var<uniform> globalParams_0 : GlobalParams_std140_0;
fn sampleDepth_0( uv_0 : vec2<f32>) -> f32
{
    var _S1 : vec2<f32> = uv_0.xy;
    return 1.0f - (textureSampleLevel((_DepthTex_0), (unity_usc_resonite_macro_sampler_0), (vec4<f32>(_S1 * globalParams_0._DepthTex_ST_0.xy + globalParams_0._DepthTex_ST_0.zw, 0.0f, 0.0f).xy), (vec4<f32>(_S1 * globalParams_0._DepthTex_ST_0.xy + globalParams_0._DepthTex_ST_0.zw, 0.0f, 0.0f).w))).x;
}

fn UnityObjectToClipPos_0( pos_0 : vec3<f32>) -> vec4<f32>
{
    return ((((((vec4<f32>(pos_0, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityObjectToClipPos_1( pos_1 : vec4<f32>) -> vec4<f32>
{
    return UnityObjectToClipPos_0(pos_1.xyz);
}

struct v2f_0
{
    @location(0) uv_1 : vec2<f32>,
    @builtin(position) vertex_0 : vec4<f32>,
    @location(1) normDepth_0 : f32,
    @location(2) diff_0 : f32,
};

struct vertexInput_0
{
    @location(0) vertex_1 : vec4<f32>,
    @location(1) uv_2 : vec2<f32>,
};

@vertex
fn vert( _S2 : vertexInput_0) -> v2f_0
{
    var depth_0 : f32 = sampleDepth_0(_S2.uv_2);
    var _S3 : f32 = sampleDepth_0(_S2.uv_2 + vec2<f32>(globalParams_0._DiscardOffset_0, 0.0f));
    var _S4 : f32 = sampleDepth_0(_S2.uv_2 + vec2<f32>(0.0f, globalParams_0._DiscardOffset_0));
    var _S5 : f32 = sampleDepth_0(_S2.uv_2 - vec2<f32>(globalParams_0._DiscardOffset_0, 0.0f));
    var _S6 : f32 = sampleDepth_0(_S2.uv_2 - vec2<f32>(0.0f, globalParams_0._DiscardOffset_0));
    var _S7 : f32 = max(max(max(abs(depth_0 - _S3), abs(depth_0 - _S4)), abs(depth_0 - _S5)), abs(depth_0 - _S6));
    var depth_1 : f32 = (depth_0 + _S3 + _S4 + _S5 + _S6) / 5.0f;
    var o_0 : v2f_0;
    o_0.normDepth_0 = depth_1;
    o_0.vertex_0 = UnityObjectToClipPos_1(vec4<f32>(vec3<f32>((_S2.uv_2 - vec2<f32>(0.5f)) * tan(globalParams_0._Angle_0.xy / vec2<f32>(180.0f) * vec2<f32>(3.14149999618530273f)), 1.0f) * vec3<f32>(((globalParams_0._DepthTo_0 - globalParams_0._DepthFrom_0) * (log(depth_1 + 1.0f) / log(globalParams_0._DepthTo_0 + 1.0f) * depth_1) + globalParams_0._DepthFrom_0)), 1.0f));
    o_0.uv_1 = _S2.uv_2;
    o_0.diff_0 = _S7;
    return o_0;
}



enable f16;

@binding(27) @group(0) var _MainTex_0 : texture_2d<f32>;

@binding(3) @group(0) var unity_usc_resonite_macro_sampler_0 : sampler;

struct GlobalParams_std140_0
{
    @align(16) unity_Lightmap_HDR_0 : vec4<f16>,
    @align(8) unity_DynamicLightmap_HDR_0 : vec4<f16>,
    @align(16) _MainTex_ST_0 : vec4<f32>,
    @align(16) _DepthTex_ST_0 : vec4<f32>,
    @align(16) _DepthFrom_0 : f32,
    @align(4) _DepthTo_0 : f32,
    @align(16) _Angle_0 : vec4<f32>,
    @align(16) _NearClip_0 : f32,
    @align(4) _FarClip_0 : f32,
    @align(8) _DiscardThreshold_0 : f32,
    @align(4) _DiscardOffset_0 : f32,
};

@binding(0) @group(0) var<uniform> globalParams_0 : GlobalParams_std140_0;
struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

struct pixelInput_0
{
    @location(0) uv_0 : vec2<f32>,
    @location(1) normDepth_0 : f32,
    @location(2) diff_0 : f32,
};

@fragment
fn frag( _S1 : pixelInput_0, @builtin(position) vertex_0 : vec4<f32>) -> pixelOutput_0
{
    var _S2 : vec4<f16> = vec4<f16>((textureSample((_MainTex_0), (unity_usc_resonite_macro_sampler_0), (_S1.uv_0.xy * globalParams_0._MainTex_ST_0.xy + globalParams_0._MainTex_ST_0.zw))));
    var _S3 : bool;
    if((_S1.diff_0) > (globalParams_0._DiscardThreshold_0))
    {
        _S3 = true;
    }
    else
    {
        _S3 = (_S1.normDepth_0) < (globalParams_0._NearClip_0);
    }
    if(_S3)
    {
        _S3 = true;
    }
    else
    {
        _S3 = (_S1.normDepth_0) > (globalParams_0._FarClip_0);
    }
    if(_S3)
    {
        discard;
    }
    var _S4 : pixelOutput_0 = pixelOutput_0( _S2 );
    return _S4;
}

