using System.Globalization;
using System.Linq;
using System.Text;
using UnityShaderConverter.Analysis;
using UnityShaderConverter.Variants;
using UnityShaderParser.ShaderLab;

namespace UnityShaderConverter.Emission;

/// <summary>Emits <c>mod.rs</c> and <c>material.rs</c> under the shader output directory (default <c>src/shaders/&lt;mod&gt;/</c>).</summary>
public static partial class RustEmitter
{
    /// <summary>Marks the end of the UnityShaderConverter block in <c>src/shaders/mod.rs</c>; hand-written <c>pub mod</c> stays below.</summary>
    public const string ShadersRootGeneratedEndMarker = "// --- END UNITY_SHADER_CONVERTER_GENERATED ---";

    /// <summary>Sanitized Rust module name (snake_case).</summary>
    public static string ModuleNameFromShaderName(string shaderName) => ShaderNaming.ModuleName(shaderName);

    /// <summary>WGSL file name for one pass when no ShaderLab <c>Name</c> is available.</summary>
    public static string WgslPassFileName(int passIndex) => $"pass{passIndex}.wgsl";

    /// <summary>WGSL file name derived from <see cref="ShaderPassDocument.PassName"/> when set.</summary>
    public static string WgslPassFileName(ShaderPassDocument pass, int passIndex) =>
        ShaderNaming.WgslPassStem(pass.PassName, passIndex) + ".wgsl";

    /// <summary>Contents of <c>mod.rs</c> inside the per-shader directory.</summary>
    public static string EmitShaderCrateModRs()
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.AppendLine();
        sb.AppendLine("pub mod material;");
        return sb.ToString();
    }

    /// <summary>Full <c>material.rs</c>: <c>VariantKey</c>, <c>Material</c>, <c>include_str!</c> per pass, wgpu helpers.</summary>
    public static string EmitShaderMaterialRs(
        ShaderFileDocument document,
        string sourcePathForComment,
        int passCount,
        IReadOnlyList<SpecializationAxis> specializationAxes,
        IReadOnlyList<PassVertexLayout> vertexLayoutsPerPass,
        uint sceneBindGroupIndex = 1,
        uint materialBindGroupIndex = 2)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.Append("//! Unity shader: `").Append(document.ShaderName).AppendLine("`");
        sb.Append("//! Source: `").Append(sourcePathForComment.Replace("\\", "/")).AppendLine("`");
        sb.AppendLine("//! One WGSL file per pass (named from ShaderLab `Name` or `passN`).");
        sb.AppendLine("//! WGSL `override` / `@id` constants use `wgpu::PipelineCompilationOptions` on vertex and fragment stages (wgpu 28).");
        sb.AppendLine("//! Texture properties on `Material` use `TextureHandle` (default `0`); host defines invalid/unbound semantics.");
        sb.AppendLine();
        sb.AppendLine("#![allow(");
        sb.AppendLine("    non_snake_case,");
        sb.AppendLine("    unused_imports,");
        sb.AppendLine("    unused_variables,");
        sb.AppendLine("    clippy::derivable_impls,");
        sb.AppendLine("    clippy::excessive_precision,");
        sb.AppendLine("    clippy::ptr_arg,");
        sb.AppendLine(")]");
        sb.AppendLine();
        sb.AppendLine("use glam::Vec4;");
        if (document.Properties.Any(static p => MaterialUniformStd140Layout.IsTexturePropertyKind(p.Kind)))
            sb.AppendLine("use crate::scene::types::TextureHandle;");
        sb.AppendLine();
        EmitVariantKeyStruct(sb, specializationAxes);
        sb.AppendLine("/// WGSL clustered scene uniforms, lights, cluster buffers (matches builtin PBR).");
        sb.Append("pub const RENDERIDE_SCENE_BIND_GROUP: u32 = ").Append(sceneBindGroupIndex.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
        sb.AppendLine("/// WGSL `MaterialUniform` and texture properties group index.");
        sb.Append("pub const MATERIAL_BIND_GROUP: u32 = ").Append(materialBindGroupIndex.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
        sb.AppendLine();
        EmitRenderideSceneBindGroupLayout(sb);
        for (int pi = 0; pi < passCount; pi++)
        {
            string file = pi < document.Passes.Count
                ? WgslPassFileName(document.Passes[pi], pi)
                : WgslPassFileName(pi);
            sb.Append("/// Merged vertex + fragment WGSL for pass ").Append(pi).AppendLine(".");
            sb.Append("pub const PASS").Append(pi).Append("_WGSL: &str = include_str!(\"");
            sb.Append(file).AppendLine("\");");
            sb.AppendLine();
        }

        sb.AppendLine("/// Default material values mapped from the Unity Properties block.");
        sb.AppendLine("#[derive(Clone, Debug, PartialEq)]");
        sb.AppendLine("pub struct Material {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            sb.Append("    pub ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(RustPropertyType(prop)).Append(", // ")
                .AppendLine(EscapeComment(prop.DisplayLabel));
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("impl Default for Material {");
        sb.AppendLine("    fn default() -> Self {");
        sb.AppendLine("        Self {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            string rustType = RustPropertyType(prop);
            string valueExpr = DefaultRustValue(prop);
            if (rustType == "f32")
                valueExpr = CoerceRustF32DefaultLiteral(valueExpr);
            sb.Append("            ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(valueExpr).AppendLine(",");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        EmitMaterialDynamicRenderStateHelpers(sb, document);
        EmitPipelineHelpers(sb, document, specializationAxes, vertexLayoutsPerPass);
        if (document.Passes.Count > 0)
        {
            for (int i = 0; i < document.Passes.Count; i++)
            {
                sb.Append("/// Vertex shader entry name produced by Slang for pass ").Append(i).AppendLine(".");
                sb.Append("pub const VERTEX_ENTRY_PASS").Append(i).Append(": &str = \"");
                sb.Append(EscapeRustString(document.Passes[i].VertexEntry!)).AppendLine("\";");
                sb.Append("pub const FRAGMENT_ENTRY_PASS").Append(i).Append(": &str = \"");
                sb.Append(EscapeRustString(document.Passes[i].FragmentEntry!)).AppendLine("\";");
                if (document.Passes[i].PragmaShaderTarget is float tgt)
                {
                    int tenths = (int)Math.Round(tgt * 10.0f, MidpointRounding.AwayFromZero);
                    sb.Append("/// First `#pragma target` in pass ").Append(i).AppendLine(" (x10 for integer const).");
                    sb.Append("pub const PRAGMA_SHADER_TARGET_PASS").Append(i).Append(": u32 = ")
                        .Append(tenths.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
                }

                sb.AppendLine();
            }

            sb.AppendLine("/// Pass names from ShaderLab (for future pipeline / file naming).");
            for (int i = 0; i < document.Passes.Count; i++)
            {
                string? pn = document.Passes[i].PassName;
                string label = string.IsNullOrEmpty(pn) ? $"pass_{i}" : pn;
                sb.Append("pub const PASS_").Append(i).Append("_NAME: &str = \"");
                sb.Append(EscapeRustString(label)).AppendLine("\";");
            }
        }

        return sb.ToString();
    }

    private static void EmitVariantKeyStruct(StringBuilder sb, IReadOnlyList<SpecializationAxis> axes)
    {
        if (axes.Count == 0)
        {
            sb.AppendLine("/// No `multi_compile` specialization axes were extracted; pipeline constants are unused.");
            sb.AppendLine("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]");
            sb.AppendLine("pub struct VariantKey;");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("/// Maps to WGSL `override` / `wgpu::PipelineCompilationOptions::constants` (decimal id keys per wgpu docs).");
        sb.AppendLine("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]");
        sb.AppendLine("pub struct VariantKey {");
        foreach (SpecializationAxis ax in axes)
        {
            sb.Append("    /// ShaderLab keyword `").Append(EscapeComment(ax.Keyword)).AppendLine("`");
            sb.Append("    pub ").Append(ax.RustFieldName).AppendLine(": bool,");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("impl Default for VariantKey {");
        sb.AppendLine("    fn default() -> Self {");
        sb.AppendLine("        Self {");
        foreach (SpecializationAxis ax in axes)
            sb.Append("            ").Append(ax.RustFieldName).AppendLine(": false,");

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitPipelineHelpers(
        StringBuilder sb,
        ShaderFileDocument document,
        IReadOnlyList<SpecializationAxis> axes,
        IReadOnlyList<PassVertexLayout> vertexLayoutsPerPass)
    {
        int passCount = document.Passes.Count;
        sb.AppendLine("/// WGSL source for use with `Device::create_shader_module`.");
        for (int pi = 0; pi < passCount; pi++)
        {
            string fnStem = ShaderNaming.WgslPassStem(document.Passes[pi].PassName, pi);
            sb.Append("pub fn shader_source_").Append(fnStem).AppendLine("() -> wgpu::ShaderSource<'static> {");
            sb.Append("    wgpu::ShaderSource::Wgsl(PASS").Append(pi).AppendLine("_WGSL.into())");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        EmitPipelineHelpersDynamicAware(sb, document, axes, vertexLayoutsPerPass);
    }

    private static void EmitPassVertexBufferLayout(StringBuilder sb, PassVertexLayout layout, int passIndex)
    {
        if (!layout.HasAttributes)
        {
            sb.Append("/// No interleaved vertex attributes were extracted for pass ").Append(passIndex);
            sb.AppendLine("; supply `vertex_layout_override` or fix WGSL.");
            sb.Append("pub static VERTEX_BUFFER_LAYOUTS_PASS").Append(passIndex);
            sb.AppendLine(": &[wgpu::VertexBufferLayout] = &[];");
            sb.AppendLine();
            return;
        }

        sb.Append("static VERTEX_ATTRIBUTES_PASS").Append(passIndex).AppendLine(": &[wgpu::VertexAttribute] = &[");
        for (int i = 0; i < layout.Attributes.Count; i++)
        {
            VertexLayoutAttribute a = layout.Attributes[i];
            uint off = layout.ByteOffsets[i];
            sb.Append("    wgpu::VertexAttribute { format: ").Append(a.RustVertexFormatPath);
            sb.Append(", offset: ").Append(off.ToString(CultureInfo.InvariantCulture));
            sb.Append(", shader_location: ").Append(a.ShaderLocation.ToString(CultureInfo.InvariantCulture));
            sb.AppendLine(" },");
        }

        sb.AppendLine("];");
        sb.Append("static VERTEX_BUFFER_LAYOUT_PASS").Append(passIndex).AppendLine(": [wgpu::VertexBufferLayout; 1] = [wgpu::VertexBufferLayout {");
        sb.Append("    array_stride: ").Append(layout.ArrayStride.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
        sb.AppendLine("    step_mode: wgpu::VertexStepMode::Vertex,");
        sb.Append("    attributes: VERTEX_ATTRIBUTES_PASS").Append(passIndex).AppendLine(",");
        sb.AppendLine("}];");
        sb.Append("pub static VERTEX_BUFFER_LAYOUTS_PASS").Append(passIndex);
        sb.Append(": &[wgpu::VertexBufferLayout] = &VERTEX_BUFFER_LAYOUT_PASS").Append(passIndex).AppendLine(";");
        sb.AppendLine();
    }

    private static void EmitSpecializationPipelineOptions(StringBuilder sb, IReadOnlyList<SpecializationAxis> axes, int passCount)
    {
        if (axes.Count > 0)
        {
            sb.AppendLine("/// Maps `VariantKey` fields to pipeline constant ids (decimal strings per WebGPU).");
            sb.AppendLine("pub fn specialization_constants_f64(variant: &VariantKey) -> std::vec::Vec<(&'static str, f64)> {");
            sb.AppendLine("    let mut v = std::vec::Vec::new();");
            foreach (SpecializationAxis ax in axes)
            {
                sb.Append("    v.push((\"");
                sb.Append(ax.ConstantId.ToString(CultureInfo.InvariantCulture));
                sb.Append("\", if variant.").Append(ax.RustFieldName).AppendLine(" { 1.0 } else { 0.0 }));");
            }

            sb.AppendLine("    v");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("static SPECIALIZATION_KEYS: &[&str] = &[");
            foreach (SpecializationAxis ax in axes)
            {
                sb.Append("    \"");
                sb.Append(ax.ConstantId.ToString(CultureInfo.InvariantCulture));
                sb.AppendLine("\",");
            }

            sb.AppendLine("];");
            sb.AppendLine();
            sb.AppendLine("fn pipeline_compilation_options_vertex_inner(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.Append("    let vals: [f64; ").Append(axes.Count.ToString(CultureInfo.InvariantCulture)).AppendLine("] = [");
            foreach (SpecializationAxis ax in axes)
            {
                sb.Append("        if variant.").Append(ax.RustFieldName).AppendLine(" { 1.0 } else { 0.0 },");
            }

            sb.AppendLine("    ];");
            sb.AppendLine("    let tuples: std::vec::Vec<(&'static str, f64)> = SPECIALIZATION_KEYS");
            sb.AppendLine("        .iter()");
            sb.AppendLine("        .copied()");
            sb.AppendLine("        .zip(vals)");
            sb.AppendLine("        .collect();");
            sb.AppendLine("    let boxed = tuples.into_boxed_slice();");
            sb.AppendLine("    let leaked = Box::leak(boxed);");
            sb.AppendLine("    wgpu::PipelineCompilationOptions {");
            sb.AppendLine("        constants: leaked,");
            sb.AppendLine("        ..Default::default()");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("fn pipeline_compilation_options_vertex_inner(_variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.AppendLine("    wgpu::PipelineCompilationOptions::default()");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("/// Builds `PipelineCompilationOptions` for vertex/fragment stages (WGSL `override` / `@id`).");
        sb.AppendLine("/// Note: leaks a tiny slice per call; cache by `VariantKey` in hot paths.");
        sb.AppendLine("/// Per-pass wrappers delegate to the same implementation (specialization is per-shader).");
        for (int pi = 0; pi < passCount; pi++)
        {
            sb.Append("pub fn pipeline_compilation_options_pass").Append(pi).AppendLine("_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.AppendLine("    pipeline_compilation_options_vertex_inner(variant)");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.Append("pub fn pipeline_compilation_options_pass").Append(pi).AppendLine("_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.AppendLine("    pipeline_compilation_options_vertex_inner(variant)");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static bool IsTexturePropertyKind(ShaderPropertyKind k) => MaterialUniformStd140Layout.IsTexturePropertyKind(k);

    /// <summary>Emits <c>push_renderide_scene_bind_group_layout_entries</c> mirroring <c>PbrPipeline</c> scene bindings.</summary>
    private static void EmitRenderideSceneBindGroupLayout(StringBuilder sb)
    {
        sb.AppendLine("/// Pushes WGSL `@group(1)` layout entries: scene uniform, light storage, cluster count/index buffers.");
        sb.AppendLine("/// Matches [`crate::gpu::pipeline::PbrPipeline`](crate::gpu::pipeline::PbrPipeline) scene group.");
        sb.AppendLine("#[allow(dead_code)]");
        sb.AppendLine("pub fn push_renderide_scene_bind_group_layout_entries(entries: &mut Vec<wgpu::BindGroupLayoutEntry>) {");
        sb.AppendLine("    use std::num::NonZeroU64;");
        sb.AppendLine("    let scene_uniform_size = std::mem::size_of::<crate::gpu::pipeline::SceneUniforms>() as u64;");
        sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
        sb.AppendLine("        binding: 0,");
        sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
        sb.AppendLine("        ty: wgpu::BindingType::Buffer {");
        sb.AppendLine("            ty: wgpu::BufferBindingType::Uniform,");
        sb.AppendLine("            has_dynamic_offset: false,");
        sb.AppendLine("            min_binding_size: NonZeroU64::new(scene_uniform_size),");
        sb.AppendLine("        },");
        sb.AppendLine("        count: None,");
        sb.AppendLine("    });");
        sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
        sb.AppendLine("        binding: 1,");
        sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
        sb.AppendLine("        ty: wgpu::BindingType::Buffer {");
        sb.AppendLine("            ty: wgpu::BufferBindingType::Storage { read_only: true },");
        sb.AppendLine("            has_dynamic_offset: false,");
        sb.AppendLine("            min_binding_size: None,");
        sb.AppendLine("        },");
        sb.AppendLine("        count: None,");
        sb.AppendLine("    });");
        sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
        sb.AppendLine("        binding: 2,");
        sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
        sb.AppendLine("        ty: wgpu::BindingType::Buffer {");
        sb.AppendLine("            ty: wgpu::BufferBindingType::Storage { read_only: true },");
        sb.AppendLine("            has_dynamic_offset: false,");
        sb.AppendLine("            min_binding_size: None,");
        sb.AppendLine("        },");
        sb.AppendLine("        count: None,");
        sb.AppendLine("    });");
        sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
        sb.AppendLine("        binding: 3,");
        sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
        sb.AppendLine("        ty: wgpu::BindingType::Buffer {");
        sb.AppendLine("            ty: wgpu::BufferBindingType::Storage { read_only: true },");
        sb.AppendLine("            has_dynamic_offset: false,");
        sb.AppendLine("            min_binding_size: None,");
        sb.AppendLine("        },");
        sb.AppendLine("        count: None,");
        sb.AppendLine("    });");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitMaterialUniformBlock(StringBuilder sb, IReadOnlyList<ShaderPropertyRecord> properties)
    {
        bool anyScalar = properties.Any(static p => !IsTexturePropertyKind(p.Kind));
        if (!anyScalar)
            return;

        (IReadOnlyList<Std140UniformField> fields, _) = MaterialUniformStd140Layout.Build(properties);
        sb.AppendLine("/// Uniform buffer layout matching the prepended WGSL `MaterialUniform` (std140 with explicit padding).");
        sb.AppendLine("#[repr(C, align(16))]");
        sb.AppendLine("#[allow(dead_code)]");
        sb.AppendLine("pub struct MaterialUniform {");
        foreach (Std140UniformField f in fields)
        {
            sb.Append("    pub ").Append(f.RustFieldName).Append(": ").Append(f.RustType).AppendLine(",");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitMaterialBindGroupRust(StringBuilder sb, IReadOnlyList<ShaderPropertyRecord> properties)
    {
        bool anyScalar = properties.Any(static p => !IsTexturePropertyKind(p.Kind));
        sb.AppendLine("/// Bind group 2: `MaterialUniform` at binding 0, then each texture + sampler pair.");
        sb.AppendLine("fn push_material_bind_group_layout_entries(entries: &mut Vec<wgpu::BindGroupLayoutEntry>) {");
        if (anyScalar)
        {
            sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
            sb.AppendLine("        binding: 0,");
            sb.AppendLine("        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,");
            sb.AppendLine("        ty: wgpu::BindingType::Buffer {");
            sb.AppendLine("            ty: wgpu::BufferBindingType::Uniform,");
            sb.AppendLine("            has_dynamic_offset: false,");
            sb.AppendLine("            min_binding_size: None,");
            sb.AppendLine("        },");
            sb.AppendLine("        count: None,");
            sb.AppendLine("    });");
        }

        uint b = 1;
        foreach (ShaderPropertyRecord prop in properties)
        {
            if (!IsTexturePropertyKind(prop.Kind))
                continue;
            sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
            sb.Append("        binding: ").Append(b.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
            sb.AppendLine("        ty: wgpu::BindingType::Texture {");
            sb.AppendLine("            sample_type: wgpu::TextureSampleType::Float { filterable: true },");
            sb.Append("            view_dimension: ");
            sb.AppendLine(TextureViewDimensionRust(prop.Kind));
            sb.AppendLine("            multisampled: false,");
            sb.AppendLine("        },");
            sb.AppendLine("        count: None,");
            sb.AppendLine("    });");
            b++;
            sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
            sb.Append("        binding: ").Append(b.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
            sb.AppendLine("        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),");
            sb.AppendLine("        count: None,");
            sb.AppendLine("    });");
            b++;
        }

        if (!anyScalar && !properties.Any(static p => IsTexturePropertyKind(p.Kind)))
            sb.AppendLine("    let _ = entries;");

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// Returns `(layout, scene_uniform_size_bytes)` for WGSL `@group(1)` clustered-forward scene data.");
        sb.AppendLine("pub fn create_renderide_scene_bind_group_layout(device: &wgpu::Device, label: &str) -> (wgpu::BindGroupLayout, u64) {");
        sb.AppendLine("    let mut entries = Vec::new();");
        sb.AppendLine("    push_renderide_scene_bind_group_layout_entries(&mut entries);");
        sb.AppendLine("    let scene_uniform_size = std::mem::size_of::<crate::gpu::pipeline::SceneUniforms>() as u64;");
        sb.AppendLine("    let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {");
        sb.AppendLine("        label: Some(label),");
        sb.AppendLine("        entries: &entries,");
        sb.AppendLine("    });");
        sb.AppendLine("    (layout, scene_uniform_size)");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("pub fn create_material_bind_group_layout(device: &wgpu::Device, label: &str) -> wgpu::BindGroupLayout {");
        sb.AppendLine("    let mut entries = Vec::new();");
        sb.AppendLine("    push_material_bind_group_layout_entries(&mut entries);");
        sb.AppendLine("    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {");
        sb.AppendLine("        label: Some(label),");
        sb.AppendLine("        entries: &entries,");
        sb.AppendLine("    })");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// `texture_views_and_samplers` must contain one `(view, sampler)` per texture property in Properties order.");
        sb.AppendLine("pub fn create_material_bind_group(");
        sb.AppendLine("    device: &wgpu::Device,");
        sb.AppendLine("    layout: &wgpu::BindGroupLayout,");
        sb.AppendLine("    label: &str,");
        sb.AppendLine("    material_uniform_buffer: &wgpu::Buffer,");
        sb.AppendLine("    texture_views_and_samplers: &[(&wgpu::TextureView, &wgpu::Sampler)],");
        sb.AppendLine(") -> wgpu::BindGroup {");
        sb.AppendLine("    let mut entries: Vec<wgpu::BindGroupEntry> = Vec::new();");
        if (!anyScalar)
            sb.AppendLine("    let _ = material_uniform_buffer;");
        if (anyScalar)
        {
            sb.AppendLine("    entries.push(wgpu::BindGroupEntry {");
            sb.AppendLine("        binding: 0,");
            sb.AppendLine("        resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {");
            sb.AppendLine("            buffer: material_uniform_buffer,");
            sb.AppendLine("            offset: 0,");
            sb.AppendLine("            size: None,");
            sb.AppendLine("        }),");
            sb.AppendLine("    });");
        }

        sb.AppendLine("    let mut b: u32 = 1;");
        sb.AppendLine("    for (view, sampler) in texture_views_and_samplers {");
        sb.AppendLine("        entries.push(wgpu::BindGroupEntry {");
        sb.AppendLine("            binding: b,");
        sb.AppendLine("            resource: wgpu::BindingResource::TextureView(view),");
        sb.AppendLine("        });");
        sb.AppendLine("        b += 1;");
        sb.AppendLine("        entries.push(wgpu::BindGroupEntry {");
        sb.AppendLine("            binding: b,");
        sb.AppendLine("            resource: wgpu::BindingResource::Sampler(sampler),");
        sb.AppendLine("        });");
        sb.AppendLine("        b += 1;");
        sb.AppendLine("    }");
        sb.AppendLine("    device.create_bind_group(&wgpu::BindGroupDescriptor { label: Some(label), layout, entries: &entries })");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string EscapeRustString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string RustFieldName(string uniformName)
    {
        string n = uniformName.TrimStart('_');
        if (n.Length == 0)
            n = "unnamed";
        string lowered = $"{char.ToLowerInvariant(n[0])}{n.AsSpan(1)}";
        return RustEscapeIdent(lowered);
    }

    private static string RustEscapeIdent(string s)
    {
        if (s.Length > 0 && char.IsDigit(s[0]))
            return "u_" + s;
        return s;
    }

    private static string TextureViewDimensionRust(ShaderPropertyKind k) =>
        k switch
        {
            ShaderPropertyKind.TextureCube => "wgpu::TextureViewDimension::Cube,",
            ShaderPropertyKind.Texture2DArray => "wgpu::TextureViewDimension::D2Array,",
            ShaderPropertyKind.TextureCubeArray => "wgpu::TextureViewDimension::CubeArray,",
            ShaderPropertyKind.Texture3D or ShaderPropertyKind.Texture3DArray => "wgpu::TextureViewDimension::D3,",
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.TextureAny => "wgpu::TextureViewDimension::D2,",
            _ => "wgpu::TextureViewDimension::D2,",
        };

    private static string RustPropertyType(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range => "f32",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int => "i32",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector => "Vec4",
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "TextureHandle",
            _ => "()",
        };

    private static string DefaultRustValue(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range =>
                prop.DefaultSummary.Length > 0 && float.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out float f)
                    ? F32Lit(f)
                    : "0.0",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int =>
                prop.DefaultSummary.Length > 0 && int.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out int i)
                    ? i.ToString(CultureInfo.InvariantCulture)
                    : "0",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector =>
                ParseVec4Default(prop.DefaultSummary),
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "0",
            _ => "()",
        };

    private static string ParseVec4Default(string summary)
    {
        ReadOnlySpan<char> s = summary.AsSpan().Trim();
        if (s.Length < 5 || s[0] != '(')
            return "Vec4::ONE";
        s = s[1..^1];
        var parts = new List<float>();
        foreach (string part in s.ToString().Split(','))
        {
            if (float.TryParse(part.Trim(), CultureInfo.InvariantCulture, out float v))
                parts.Add(v);
        }

        if (parts.Count >= 4)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, {F32Lit(parts[3])})";
        if (parts.Count == 3)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, 1.0)";
        return "Vec4::ONE";
    }

    private static string F32Lit(float x)
    {
        string s = x.ToString("G9", CultureInfo.InvariantCulture);
        if (!s.Contains('.') && !s.Contains('E') && !s.Contains('e'))
            s += ".0";
        return s;
    }

    /// <summary>
    /// Unity ShaderLab sometimes stores <c>Range</c> defaults as integers; <see cref="DefaultRustValue"/> may
    /// emit <c>4</c> while the Rust field is <c>f32</c>. Parses and rewrites with <see cref="F32Lit"/>.
    /// </summary>
    private static string CoerceRustF32DefaultLiteral(string expr)
    {
        if (float.TryParse(expr, NumberStyles.Float, CultureInfo.InvariantCulture, out float f))
            return F32Lit(f);
        return expr;
    }

    private static string EscapeComment(string s) => s.Replace("*/", "* /");
}
