using System.Globalization;
using System.Text;
using UnityShaderConverter.Analysis;
using UnityShaderConverter.Variants;
using UnityShaderParser.ShaderLab;

namespace UnityShaderConverter.Emission;

/// <summary>Emits <c>mod.rs</c> and <c>material.rs</c> under <c>crates/renderide/src/shaders/&lt;mod&gt;/</c>.</summary>
public static class RustEmitter
{
    /// <summary>Sanitized Rust module name (snake_case).</summary>
    public static string ModuleNameFromShaderName(string shaderName) => ShaderNaming.ModuleName(shaderName);

    /// <summary>WGSL file name for one pass (sits next to <c>material.rs</c>).</summary>
    public static string WgslPassFileName(int passIndex) => $"pass{passIndex}.wgsl";

    /// <summary>Contents of <c>mod.rs</c> inside the per-shader directory.</summary>
    public static string EmitShaderCrateModRs()
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.AppendLine();
        sb.AppendLine("pub mod material;");
        return sb.ToString();
    }

    /// <summary>Full <c>material.rs</c>: <c>VariantKey</c>, <c>Material</c>, <c>include_str!</c> per pass, wgpu helpers.</summary>
    public static string EmitShaderMaterialRs(
        ShaderFileDocument document,
        string sourcePathForComment,
        int passCount,
        IReadOnlyList<SpecializationAxis> specializationAxes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.Append("//! Unity shader: `").Append(document.ShaderName).AppendLine("`");
        sb.Append("//! Source: `").Append(sourcePathForComment.Replace("\\", "/")).AppendLine("`");
        sb.AppendLine("//! One WGSL file per pass (`passN.wgsl`). Variants use WGSL `override` via `wgpu::PipelineCompilationOptions` when specialization is enabled.");
        sb.AppendLine();
        sb.AppendLine("use glam::Vec4;");
        sb.AppendLine();
        EmitVariantKeyStruct(sb, specializationAxes);
        for (int pi = 0; pi < passCount; pi++)
        {
            string file = WgslPassFileName(pi);
            sb.Append("/// Merged vertex + fragment WGSL for pass ").Append(pi).AppendLine(".");
            sb.Append("pub const PASS").Append(pi).Append("_WGSL: &str = include_str!(\"");
            sb.Append(file).AppendLine("\");");
            sb.AppendLine();
        }

        sb.AppendLine("/// Default material values mapped from the Unity Properties block.");
        sb.AppendLine("#[derive(Clone, Debug, PartialEq)]");
        sb.AppendLine("pub struct Material {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            sb.Append("    pub ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(RustPropertyType(prop)).Append(", // ")
                .AppendLine(EscapeComment(prop.DisplayLabel));
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("impl Default for Material {");
        sb.AppendLine("    fn default() -> Self {");
        sb.AppendLine("        Self {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            sb.Append("            ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(DefaultRustValue(prop)).AppendLine(",");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        EmitPipelineHelpers(sb, passCount, specializationAxes, document);
        if (document.Passes.Count > 0)
        {
            sb.AppendLine("/// Vertex shader entry name produced by Slang for pass 0.");
            sb.Append("pub const VERTEX_ENTRY_PASS0: &str = \"");
            sb.Append(EscapeRustString(document.Passes[0].VertexEntry!)).AppendLine("\";");
            sb.Append("pub const FRAGMENT_ENTRY_PASS0: &str = \"");
            sb.Append(EscapeRustString(document.Passes[0].FragmentEntry!)).AppendLine("\";");
            sb.AppendLine();
            sb.AppendLine("/// Pass names from ShaderLab (for future pipeline / file naming).");
            for (int i = 0; i < document.Passes.Count; i++)
            {
                string? pn = document.Passes[i].PassName;
                string label = string.IsNullOrEmpty(pn) ? $"pass_{i}" : pn;
                sb.Append("pub const PASS_").Append(i).Append("_NAME: &str = \"");
                sb.Append(EscapeRustString(label)).AppendLine("\";");
            }
        }

        return sb.ToString();
    }

    private static void EmitVariantKeyStruct(StringBuilder sb, IReadOnlyList<SpecializationAxis> axes)
    {
        if (axes.Count == 0)
        {
            sb.AppendLine("/// No `multi_compile` specialization axes were extracted; pipeline constants are unused.");
            sb.AppendLine("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]");
            sb.AppendLine("pub struct VariantKey;");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("/// Maps to WGSL `override` / `wgpu::PipelineCompilationOptions::constants` (decimal id keys per wgpu docs).");
        sb.AppendLine("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]");
        sb.AppendLine("pub struct VariantKey {");
        foreach (SpecializationAxis ax in axes)
        {
            sb.Append("    /// ShaderLab keyword `").Append(EscapeComment(ax.Keyword)).AppendLine("`");
            sb.Append("    pub ").Append(ax.RustFieldName).AppendLine(": bool,");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("impl Default for VariantKey {");
        sb.AppendLine("    fn default() -> Self {");
        sb.AppendLine("        Self {");
        foreach (SpecializationAxis ax in axes)
            sb.Append("            ").Append(ax.RustFieldName).AppendLine(": false,");

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitPipelineHelpers(
        StringBuilder sb,
        int passCount,
        IReadOnlyList<SpecializationAxis> axes,
        ShaderFileDocument document)
    {
        sb.AppendLine("/// WGSL source for use with `Device::create_shader_module`.");
        sb.AppendLine("pub fn shader_source_pass0() -> wgpu::ShaderSource<'static> {");
        sb.AppendLine("    wgpu::ShaderSource::Wgsl(PASS0_WGSL.into())");
        sb.AppendLine("}");
        sb.AppendLine();
        for (int pi = 1; pi < passCount; pi++)
        {
            sb.Append("pub fn shader_source_pass").Append(pi).AppendLine("() -> wgpu::ShaderSource<'static> {");
            sb.Append("    wgpu::ShaderSource::Wgsl(PASS").Append(pi).AppendLine("_WGSL.into())");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (axes.Count > 0)
        {
            sb.AppendLine("/// Maps `VariantKey` fields to `wgpu::PipelineCompilationOptions::constants` (decimal id keys).");
            sb.AppendLine("/// Build a `Vec<(&'static str, f64)>` or fixed array when wiring real pipelines.");
            sb.AppendLine("pub fn specialization_constants_f64(variant: &VariantKey) -> std::vec::Vec<(&'static str, f64)> {");
            sb.AppendLine("    let mut v = std::vec::Vec::new();");
            foreach (SpecializationAxis ax in axes)
            {
                sb.Append("    v.push((\"");
                sb.Append(ax.ConstantId.ToString(CultureInfo.InvariantCulture));
                sb.Append("\", if variant.").Append(ax.RustFieldName).AppendLine(" { 1.0 } else { 0.0 }));");
            }

            sb.AppendLine("    v");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("/// Defaults until you map `specialization_constants_f64` into a leaked or cached slice for `constants`.");
        sb.AppendLine("pub fn pipeline_compilation_options_pass0_vertex(_variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
        sb.AppendLine("    wgpu::PipelineCompilationOptions::default()");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("pub fn pipeline_compilation_options_pass0_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
        sb.AppendLine("    pipeline_compilation_options_pass0_vertex(variant)");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// Placeholder bind group layout entries for material uniforms (group 1).");
        sb.AppendLine("pub fn material_bind_group_layout_entries() -> &'static [wgpu::BindGroupLayoutEntry] {");
        sb.AppendLine("    &[]");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("pub fn create_material_bind_group_layout(device: &wgpu::Device, label: &str) -> wgpu::BindGroupLayout {");
        sb.AppendLine("    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {");
        sb.AppendLine("        label: Some(label),");
        sb.AppendLine("        entries: material_bind_group_layout_entries(),");
        sb.AppendLine("    })");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("pub fn color_target_state(format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {");
        sb.AppendLine("    Some(wgpu::ColorTargetState {");
        sb.AppendLine("        format,");
        sb.AppendLine("        blend: None,");
        sb.AppendLine("        write_mask: wgpu::ColorWrites::ALL,");
        sb.AppendLine("    })");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// Builds a render pipeline using pass 0 WGSL (stub — extend with real layouts and vertex buffers).");
        sb.AppendLine("pub fn create_render_pipeline_pass0_stub(");
        sb.AppendLine("    device: &wgpu::Device,");
        sb.AppendLine("    label: &str,");
        sb.AppendLine("    layout: &wgpu::PipelineLayout,");
        sb.AppendLine("    surface_format: wgpu::TextureFormat,");
        sb.AppendLine("    variant: &VariantKey,");
        sb.AppendLine(") -> wgpu::RenderPipeline {");
        sb.AppendLine("    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {");
        sb.Append("        label: Some(");
        sb.Append('"').Append(EscapeRustString(document.ShaderName)).AppendLine("\"),");
        sb.AppendLine("        source: shader_source_pass0(),");
        sb.AppendLine("    });");
        sb.AppendLine("    let vertex_opts = pipeline_compilation_options_pass0_vertex(variant);");
        sb.AppendLine("    let fragment_opts = pipeline_compilation_options_pass0_fragment(variant);");
        sb.AppendLine("    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {");
        sb.AppendLine("        label: Some(label),");
        sb.AppendLine("        layout: Some(layout),");
        sb.AppendLine("        vertex: wgpu::VertexState {");
        sb.AppendLine("            module: &module,");
        if (document.Passes.Count > 0)
        {
            sb.Append("            entry_point: Some(\"");
            sb.Append(EscapeRustString(document.Passes[0].VertexEntry!));
            sb.AppendLine("\"),");
        }
        else
            sb.AppendLine("            entry_point: None,");

        sb.AppendLine("            buffers: &[],");
        sb.AppendLine("            compilation_options: vertex_opts,");
        sb.AppendLine("        },");
        sb.AppendLine("        fragment: Some(wgpu::FragmentState {");
        sb.AppendLine("            module: &module,");
        if (document.Passes.Count > 0)
        {
            sb.Append("            entry_point: Some(\"");
            sb.Append(EscapeRustString(document.Passes[0].FragmentEntry!));
            sb.AppendLine("\"),");
        }
        else
            sb.AppendLine("            entry_point: None,");

        sb.AppendLine("            targets: &[Some(wgpu::ColorTargetState {");
        sb.AppendLine("                format: surface_format,");
        sb.AppendLine("                blend: None,");
        sb.AppendLine("                write_mask: wgpu::ColorWrites::ALL,");
        sb.AppendLine("            })],");
        sb.AppendLine("            compilation_options: fragment_opts,");
        sb.AppendLine("        }),");
        sb.AppendLine("        primitive: wgpu::PrimitiveState::default(),");
        sb.AppendLine("        depth_stencil: None,");
        sb.AppendLine("        multisample: wgpu::MultisampleState::default(),");
        sb.AppendLine("        multiview_mask: None,");
        sb.AppendLine("        cache: None,");
        sb.AppendLine("    })");
        sb.AppendLine("}");
    }

    private static string EscapeRustString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string RustFieldName(string uniformName)
    {
        string n = uniformName.TrimStart('_');
        if (n.Length == 0)
            n = "unnamed";
        string lowered = $"{char.ToLowerInvariant(n[0])}{n.AsSpan(1)}";
        return RustEscapeIdent(lowered);
    }

    private static string RustEscapeIdent(string s)
    {
        if (s.Length > 0 && char.IsDigit(s[0]))
            return "u_" + s;
        return s;
    }

    private static string RustPropertyType(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range => "f32",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int => "i32",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector => "Vec4",
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "u32",
            _ => "()",
        };

    private static string DefaultRustValue(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range =>
                prop.DefaultSummary.Length > 0 && float.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out float f)
                    ? f.ToString(CultureInfo.InvariantCulture)
                    : "0.0",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int =>
                prop.DefaultSummary.Length > 0 && int.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out int i)
                    ? i.ToString(CultureInfo.InvariantCulture)
                    : "0",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector =>
                ParseVec4Default(prop.DefaultSummary),
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "0",
            _ => "()",
        };

    private static string ParseVec4Default(string summary)
    {
        ReadOnlySpan<char> s = summary.AsSpan().Trim();
        if (s.Length < 5 || s[0] != '(')
            return "Vec4::ONE";
        s = s[1..^1];
        var parts = new List<float>();
        foreach (string part in s.ToString().Split(','))
        {
            if (float.TryParse(part.Trim(), CultureInfo.InvariantCulture, out float v))
                parts.Add(v);
        }

        if (parts.Count >= 4)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, {F32Lit(parts[3])})";
        if (parts.Count == 3)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, 1.0)";
        return "Vec4::ONE";
    }

    private static string F32Lit(float x)
    {
        string s = x.ToString("G9", CultureInfo.InvariantCulture);
        if (!s.Contains('.') && !s.Contains('E') && !s.Contains('e'))
            s += ".0";
        return s;
    }

    private static string EscapeComment(string s) => s.Replace("*/", "* /");
}
