using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityShaderConverter.Analysis;
using UnityShaderConverter.Variants;
using UnityShaderParser.ShaderLab;

namespace UnityShaderConverter.Emission;

/// <summary>Emits <c>mod.rs</c> and <c>material.rs</c> under the shader output directory (default <c>src/shaders/&lt;mod&gt;/</c>).</summary>
public static partial class RustEmitter
{
    /// <summary>Marks the end of the UnityShaderConverter block in <c>src/shaders/mod.rs</c>; hand-written <c>pub mod</c> stays below.</summary>
    public const string ShadersRootGeneratedEndMarker = "// --- END UNITY_SHADER_CONVERTER_GENERATED ---";

    /// <summary>Sanitized Rust module name (snake_case).</summary>
    public static string ModuleNameFromShaderName(string shaderName) => ShaderNaming.ModuleName(shaderName);

    /// <summary>WGSL file name for one pass when no ShaderLab <c>Name</c> is available.</summary>
    public static string WgslPassFileName(int passIndex) => $"pass{passIndex}.wgsl";

    /// <summary>WGSL file name derived from <see cref="ShaderPassDocument.PassName"/> when set.</summary>
    public static string WgslPassFileName(ShaderPassDocument pass, int passIndex) =>
        ShaderNaming.WgslPassStem(pass.PassName, passIndex) + ".wgsl";

    /// <summary>Contents of <c>mod.rs</c> inside the per-shader directory.</summary>
    public static string EmitShaderCrateModRs()
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.AppendLine();
        sb.AppendLine("pub mod material;");
        return sb.ToString();
    }

    /// <summary>Full <c>material.rs</c>: <c>VariantKey</c>, <c>Material</c>, <c>include_str!</c> per pass, wgpu helpers.</summary>
    public static string EmitShaderMaterialRs(
        ShaderFileDocument document,
        string sourcePathForComment,
        int passCount,
        IReadOnlyList<SpecializationAxis> specializationAxes,
        IReadOnlyList<PassVertexLayout> vertexLayoutsPerPass)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.Append("//! Unity shader: `").Append(document.ShaderName).AppendLine("`");
        sb.Append("//! Source: `").Append(sourcePathForComment.Replace("\\", "/")).AppendLine("`");
        sb.AppendLine("//! One WGSL file per pass (named from ShaderLab `Name` or `passN`).");
        sb.AppendLine("//! WGSL `override` / `@id` constants use `wgpu::PipelineCompilationOptions` on vertex and fragment stages (wgpu 28).");
        sb.AppendLine("//! Texture properties on `Material` use `TextureHandle` (default `0`); host defines invalid/unbound semantics.");
        sb.AppendLine();
        sb.AppendLine("use glam::Vec4;");
        if (document.Properties.Any(static p => MaterialUniformStd140Layout.IsTexturePropertyKind(p.Kind)))
            sb.AppendLine("use crate::scene::types::TextureHandle;");
        sb.AppendLine();
        EmitVariantKeyStruct(sb, specializationAxes);
        for (int pi = 0; pi < passCount; pi++)
        {
            string file = pi < document.Passes.Count
                ? WgslPassFileName(document.Passes[pi], pi)
                : WgslPassFileName(pi);
            sb.Append("/// Merged vertex + fragment WGSL for pass ").Append(pi).AppendLine(".");
            sb.Append("pub const PASS").Append(pi).Append("_WGSL: &str = include_str!(\"");
            sb.Append(file).AppendLine("\");");
            sb.AppendLine();
        }

        sb.AppendLine("/// Default material values mapped from the Unity Properties block.");
        sb.AppendLine("#[derive(Clone, Debug, PartialEq)]");
        sb.AppendLine("pub struct Material {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            sb.Append("    pub ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(RustPropertyType(prop)).Append(", // ")
                .AppendLine(EscapeComment(prop.DisplayLabel));
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("impl Default for Material {");
        sb.AppendLine("    fn default() -> Self {");
        sb.AppendLine("        Self {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            sb.Append("            ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(DefaultRustValue(prop)).AppendLine(",");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        EmitPipelineHelpers(sb, document, specializationAxes, vertexLayoutsPerPass);
        if (document.Passes.Count > 0)
        {
            for (int i = 0; i < document.Passes.Count; i++)
            {
                sb.Append("/// Vertex shader entry name produced by Slang for pass ").Append(i).AppendLine(".");
                sb.Append("pub const VERTEX_ENTRY_PASS").Append(i).Append(": &str = \"");
                sb.Append(EscapeRustString(document.Passes[i].VertexEntry!)).AppendLine("\";");
                sb.Append("pub const FRAGMENT_ENTRY_PASS").Append(i).Append(": &str = \"");
                sb.Append(EscapeRustString(document.Passes[i].FragmentEntry!)).AppendLine("\";");
                sb.AppendLine();
            }

            sb.AppendLine("/// Pass names from ShaderLab (for future pipeline / file naming).");
            for (int i = 0; i < document.Passes.Count; i++)
            {
                string? pn = document.Passes[i].PassName;
                string label = string.IsNullOrEmpty(pn) ? $"pass_{i}" : pn;
                sb.Append("pub const PASS_").Append(i).Append("_NAME: &str = \"");
                sb.Append(EscapeRustString(label)).AppendLine("\";");
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Extracts Rust module names from <c>pub mod name;</c> lines inside the UnityShaderConverter-generated section of <paramref name="existingRootModRs"/>.
    /// </summary>
    /// <returns>Names in file order; empty when markers are missing.</returns>
    public static IReadOnlyList<string> ListConverterGeneratedModNamesInExistingRoot(string? existingRootModRs)
    {
        if (string.IsNullOrEmpty(existingRootModRs))
            return Array.Empty<string>();

        int start = existingRootModRs.IndexOf("// GENERATED BY UnityShaderConverter", StringComparison.Ordinal);
        if (start < 0)
            return Array.Empty<string>();

        int end = existingRootModRs.IndexOf(ShadersRootGeneratedEndMarker, start, StringComparison.Ordinal);
        if (end < 0)
            return Array.Empty<string>();

        string section = existingRootModRs[start..end];
        var names = new List<string>();
        foreach (Match m in GeneratedPubModRegex().Matches(section))
        {
            if (m.Groups.Count > 1)
                names.Add(m.Groups[1].Value);
        }

        return names;
    }

    [GeneratedRegex(@"^\s*pub\s+mod\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*;\s*$", RegexOptions.Multiline)]
    private static partial Regex GeneratedPubModRegex();

    /// <summary>Merges sorted <c>pub mod &lt;shader_stem&gt;;</c> lines into the crate <c>shaders/mod.rs</c>, preserving the tail below the end marker.</summary>
    /// <param name="existingRootModRs">Current file text, or <c>null</c> if missing.</param>
    /// <param name="successModNames">Rust module names written successfully this run.</param>
    /// <param name="preservedFailedModNames">Module names that failed this run but must stay declared (and protected from stale cleanup).</param>
    public static string MergeShadersRootModRs(
        string? existingRootModRs,
        IReadOnlyList<string> successModNames,
        IReadOnlyList<string>? preservedFailedModNames = null)
    {
        var union = new HashSet<string>(StringComparer.Ordinal);
        foreach (string s in successModNames)
            union.Add(s);
        foreach (string s in preservedFailedModNames ?? Array.Empty<string>())
            union.Add(s);
        foreach (string s in ListConverterGeneratedModNamesInExistingRoot(existingRootModRs))
            union.Add(s);

        var merged = union.ToList();
        merged.Sort(StringComparer.Ordinal);
        string block = BuildShadersRootGeneratedBlock(merged);

        if (string.IsNullOrEmpty(existingRootModRs))
        {
            return "//! UnityShaderConverter emits one subdirectory per shader here (e.g. `pbs_metallic/material.rs`).\n"
                + "//! Add hand-written shader modules below the end marker to avoid merge conflicts.\n\n"
                + block;
        }

        string text = existingRootModRs;
        int markerIdx = text.IndexOf(ShadersRootGeneratedEndMarker, StringComparison.Ordinal);
        string tail;
        int docSearchLimit = text.Length;
        if (markerIdx >= 0)
        {
            int tailStart = markerIdx + ShadersRootGeneratedEndMarker.Length;
            tail = tailStart < text.Length ? text[tailStart..].TrimStart('\r', '\n') : "";
            docSearchLimit = markerIdx;
        }
        else
        {
            int cfgTest = text.IndexOf("#[cfg(test)]", StringComparison.Ordinal);
            if (cfgTest >= 0)
            {
                tail = text[cfgTest..].TrimStart('\r', '\n');
                docSearchLimit = cfgTest;
            }
            else
                tail = "";
        }

        string headDoc = ExtractLeadingModuleDocs(text, docSearchLimit);
        if (headDoc.Length == 0)
        {
            headDoc = "//! UnityShaderConverter emits one subdirectory per shader in this module. Hand-written modules go below the end marker.\n";
        }

        string tailOut = tail.Length > 0 ? "\n" + tail.TrimStart() + (tail.TrimEnd().EndsWith('\n') ? "" : "\n") : "\n";
        return headDoc.TrimEnd() + "\n\n" + block + tailOut;
    }

    /// <summary>Builds the marker-delimited block: header comment, one <c>pub mod</c> per name (sorted, distinct), then the end marker.</summary>
    private static string BuildShadersRootGeneratedBlock(IReadOnlyList<string> converterShaderModNames)
    {
        var names = new List<string>(converterShaderModNames.Distinct(StringComparer.Ordinal));
        names.Sort(StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// GENERATED BY UnityShaderConverter — do not edit between this line and the end marker.");
        foreach (string m in names)
            sb.Append("pub mod ").Append(m).AppendLine(";");
        sb.AppendLine(ShadersRootGeneratedEndMarker);
        return sb.ToString();
    }

    private static string ExtractLeadingModuleDocs(string text, int searchLimit)
    {
        int limit = Math.Min(searchLimit, text.Length);
        var lines = text.AsSpan(0, limit).ToString().Split('\n');
        var doc = new StringBuilder();
        int i = 0;
        while (i < lines.Length)
        {
            string line = lines[i].TrimEnd('\r');
            string t = line.TrimStart();
            if (t.StartsWith("//!", StringComparison.Ordinal))
            {
                doc.AppendLine(line);
                i++;
                continue;
            }

            if (string.IsNullOrWhiteSpace(line))
            {
                if (doc.Length > 0)
                    doc.AppendLine();
                i++;
                continue;
            }

            break;
        }

        return doc.ToString().TrimEnd();
    }

    private static void EmitVariantKeyStruct(StringBuilder sb, IReadOnlyList<SpecializationAxis> axes)
    {
        if (axes.Count == 0)
        {
            sb.AppendLine("/// No `multi_compile` specialization axes were extracted; pipeline constants are unused.");
            sb.AppendLine("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]");
            sb.AppendLine("pub struct VariantKey;");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("/// Maps to WGSL `override` / `wgpu::PipelineCompilationOptions::constants` (decimal id keys per wgpu docs).");
        sb.AppendLine("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]");
        sb.AppendLine("pub struct VariantKey {");
        foreach (SpecializationAxis ax in axes)
        {
            sb.Append("    /// ShaderLab keyword `").Append(EscapeComment(ax.Keyword)).AppendLine("`");
            sb.Append("    pub ").Append(ax.RustFieldName).AppendLine(": bool,");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("impl Default for VariantKey {");
        sb.AppendLine("    fn default() -> Self {");
        sb.AppendLine("        Self {");
        foreach (SpecializationAxis ax in axes)
            sb.Append("            ").Append(ax.RustFieldName).AppendLine(": false,");

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitPipelineHelpers(
        StringBuilder sb,
        ShaderFileDocument document,
        IReadOnlyList<SpecializationAxis> axes,
        IReadOnlyList<PassVertexLayout> vertexLayoutsPerPass)
    {
        int passCount = document.Passes.Count;
        sb.AppendLine("/// WGSL source for use with `Device::create_shader_module`.");
        for (int pi = 0; pi < passCount; pi++)
        {
            string fnStem = ShaderNaming.WgslPassStem(document.Passes[pi].PassName, pi);
            sb.Append("pub fn shader_source_").Append(fnStem).AppendLine("() -> wgpu::ShaderSource<'static> {");
            sb.Append("    wgpu::ShaderSource::Wgsl(PASS").Append(pi).AppendLine("_WGSL.into())");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        for (int pi = 0; pi < passCount; pi++)
        {
            PassVertexLayout vLayout = pi < vertexLayoutsPerPass.Count ? vertexLayoutsPerPass[pi] : PassVertexLayout.Empty;
            EmitPassVertexBufferLayout(sb, vLayout, pi);
        }

        EmitMaterialUniformBlock(sb, document.Properties);

        EmitSpecializationPipelineOptions(sb, axes, passCount);
        EmitMaterialBindGroupRust(sb, document.Properties);

        for (int pi = 0; pi < passCount; pi++)
        {
            PassFixedFunctionState ff = document.Passes[pi].FixedFunctionState;
            sb.Append("/// Primitive assembly for pass ").Append(pi).Append(" (from ShaderLab `Cull`)");
            if (ff.EffectiveTags.Count > 0)
            {
                sb.Append(". Tags: ");
                sb.Append(
                    string.Join(
                        "; ",
                        ff.EffectiveTags.OrderBy(static k => k.Key, StringComparer.Ordinal)
                            .Select(kv => $"`{EscapeComment(kv.Key)}` = `{EscapeComment(kv.Value)}`")));
            }

            sb.AppendLine(".");
            sb.Append("pub fn primitive_state_pass").Append(pi).AppendLine("() -> wgpu::PrimitiveState {");
            sb.AppendLine(FixedFunctionRustEmitter.EmitPrimitiveState(ff));
            sb.AppendLine("}");
            sb.AppendLine();
            sb.Append("/// Depth/stencil for pass ").Append(pi).Append(" when a depth attachment is used.");
            sb.AppendLine();
            sb.Append("pub fn depth_stencil_state_pass").Append(pi).AppendLine("(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {");
            sb.AppendLine(FixedFunctionRustEmitter.EmitDepthStencilState(ff, "depth_format"));
            sb.AppendLine("}");
            sb.AppendLine();
            sb.Append("/// First color target for pass ").Append(pi).Append(" (blend + write mask from ShaderLab).");
            sb.AppendLine();
            sb.Append("pub fn color_target_state_pass").Append(pi).AppendLine("(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {");
            sb.Append("    ");
            sb.AppendLine(FixedFunctionRustEmitter.EmitColorTargetState(ff, "surface_format"));
            sb.AppendLine("}");
            sb.AppendLine();
        }

        for (int pi = 0; pi < passCount; pi++)
        {
            string fnStem = ShaderNaming.WgslPassStem(document.Passes[pi].PassName, pi);
            sb.Append("/// Builds a render pipeline for pass ").Append(pi).Append(" using generated fixed-function state.");
            sb.AppendLine();
            sb.Append("pub fn create_render_pipeline_pass").Append(pi).AppendLine("(");
            sb.AppendLine("    device: &wgpu::Device,");
            sb.AppendLine("    label: &str,");
            sb.AppendLine("    layout: &wgpu::PipelineLayout,");
            sb.AppendLine("    surface_format: wgpu::TextureFormat,");
            sb.AppendLine("    depth_format: Option<wgpu::TextureFormat>,");
            sb.AppendLine("    variant: &VariantKey,");
            sb.AppendLine("    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,");
            sb.AppendLine(") -> wgpu::RenderPipeline {");
            sb.Append("    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override {");
            sb.Append(" Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS").Append(pi).AppendLine(" };");
            sb.AppendLine("    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {");
            sb.Append("        label: Some(");
            sb.Append('"').Append(EscapeRustString(document.ShaderName)).AppendLine("\"),");
            sb.Append("        source: shader_source_").Append(fnStem).AppendLine("(),");
            sb.AppendLine("    });");
            sb.Append("    let vertex_opts = pipeline_compilation_options_pass").Append(pi).AppendLine("_vertex(variant);");
            sb.Append("    let fragment_opts = pipeline_compilation_options_pass").Append(pi).AppendLine("_fragment(variant);");
            sb.AppendLine("    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {");
            sb.AppendLine("        label: Some(label),");
            sb.AppendLine("        layout: Some(layout),");
            sb.AppendLine("        vertex: wgpu::VertexState {");
            sb.AppendLine("            module: &module,");
            sb.Append("            entry_point: Some(\"");
            sb.Append(EscapeRustString(document.Passes[pi].VertexEntry!));
            sb.AppendLine("\"),");
            sb.AppendLine("            buffers: vertex_buffers,");
            sb.AppendLine("            compilation_options: vertex_opts,");
            sb.AppendLine("        },");
            sb.AppendLine("        fragment: Some(wgpu::FragmentState {");
            sb.AppendLine("            module: &module,");
            sb.Append("            entry_point: Some(\"");
            sb.Append(EscapeRustString(document.Passes[pi].FragmentEntry!));
            sb.AppendLine("\"),");
            sb.Append("            targets: &[color_target_state_pass").Append(pi).AppendLine("(surface_format)],");
            sb.AppendLine("            compilation_options: fragment_opts,");
            sb.AppendLine("        }),");
            sb.Append("        primitive: primitive_state_pass").Append(pi).AppendLine("(),");
            sb.Append("        depth_stencil: depth_format.map(depth_stencil_state_pass").Append(pi).AppendLine("),");
            sb.AppendLine("        multisample: wgpu::MultisampleState::default(),");
            sb.AppendLine("        multiview_mask: None,");
            sb.AppendLine("        cache: None,");
            sb.AppendLine("    })");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        EmitCreateRenderPipelineDispatcher(sb, passCount);
    }

    private static void EmitPassVertexBufferLayout(StringBuilder sb, PassVertexLayout layout, int passIndex)
    {
        if (!layout.HasAttributes)
        {
            sb.Append("/// No interleaved vertex attributes were extracted for pass ").Append(passIndex);
            sb.AppendLine("; supply `vertex_layout_override` or fix WGSL.");
            sb.Append("pub static VERTEX_BUFFER_LAYOUTS_PASS").Append(passIndex);
            sb.AppendLine(": &[wgpu::VertexBufferLayout] = &[];");
            sb.AppendLine();
            return;
        }

        sb.Append("static VERTEX_ATTRIBUTES_PASS").Append(passIndex).AppendLine(": &[wgpu::VertexAttribute] = &[");
        for (int i = 0; i < layout.Attributes.Count; i++)
        {
            VertexLayoutAttribute a = layout.Attributes[i];
            uint off = layout.ByteOffsets[i];
            sb.Append("    wgpu::VertexAttribute { format: ").Append(a.RustVertexFormatPath);
            sb.Append(", offset: ").Append(off.ToString(CultureInfo.InvariantCulture));
            sb.Append(", shader_location: ").Append(a.ShaderLocation.ToString(CultureInfo.InvariantCulture));
            sb.AppendLine(" },");
        }

        sb.AppendLine("];");
        sb.Append("static VERTEX_BUFFER_LAYOUT_PASS").Append(passIndex).AppendLine(": [wgpu::VertexBufferLayout; 1] = [wgpu::VertexBufferLayout {");
        sb.Append("    array_stride: ").Append(layout.ArrayStride.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
        sb.AppendLine("    step_mode: wgpu::VertexStepMode::Vertex,");
        sb.Append("    attributes: VERTEX_ATTRIBUTES_PASS").Append(passIndex).AppendLine(",");
        sb.AppendLine("}];");
        sb.Append("pub static VERTEX_BUFFER_LAYOUTS_PASS").Append(passIndex);
        sb.Append(": &[wgpu::VertexBufferLayout] = &VERTEX_BUFFER_LAYOUT_PASS").Append(passIndex).AppendLine(";");
        sb.AppendLine();
    }

    private static void EmitSpecializationPipelineOptions(StringBuilder sb, IReadOnlyList<SpecializationAxis> axes, int passCount)
    {
        if (axes.Count > 0)
        {
            sb.AppendLine("/// Maps `VariantKey` fields to pipeline constant ids (decimal strings per WebGPU).");
            sb.AppendLine("pub fn specialization_constants_f64(variant: &VariantKey) -> std::vec::Vec<(&'static str, f64)> {");
            sb.AppendLine("    let mut v = std::vec::Vec::new();");
            foreach (SpecializationAxis ax in axes)
            {
                sb.Append("    v.push((\"");
                sb.Append(ax.ConstantId.ToString(CultureInfo.InvariantCulture));
                sb.Append("\", if variant.").Append(ax.RustFieldName).AppendLine(" { 1.0 } else { 0.0 }));");
            }

            sb.AppendLine("    v");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("static SPECIALIZATION_KEYS: &[&str] = &[");
            foreach (SpecializationAxis ax in axes)
            {
                sb.Append("    \"");
                sb.Append(ax.ConstantId.ToString(CultureInfo.InvariantCulture));
                sb.AppendLine("\",");
            }

            sb.AppendLine("];");
            sb.AppendLine();
            sb.AppendLine("fn pipeline_compilation_options_vertex_inner(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.Append("    let vals: [f64; ").Append(axes.Count.ToString(CultureInfo.InvariantCulture)).AppendLine("] = [");
            foreach (SpecializationAxis ax in axes)
            {
                sb.Append("        if variant.").Append(ax.RustFieldName).AppendLine(" { 1.0 } else { 0.0 },");
            }

            sb.AppendLine("    ];");
            sb.AppendLine("    let tuples: std::vec::Vec<(&'static str, f64)> = SPECIALIZATION_KEYS");
            sb.AppendLine("        .iter()");
            sb.AppendLine("        .copied()");
            sb.AppendLine("        .zip(vals)");
            sb.AppendLine("        .collect();");
            sb.AppendLine("    let boxed = tuples.into_boxed_slice();");
            sb.AppendLine("    let leaked = Box::leak(boxed);");
            sb.AppendLine("    wgpu::PipelineCompilationOptions {");
            sb.AppendLine("        constants: leaked,");
            sb.AppendLine("        ..Default::default()");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("fn pipeline_compilation_options_vertex_inner(_variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.AppendLine("    wgpu::PipelineCompilationOptions::default()");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("/// Builds `PipelineCompilationOptions` for vertex/fragment stages (WGSL `override` / `@id`).");
        sb.AppendLine("/// Note: leaks a tiny slice per call; cache by `VariantKey` in hot paths.");
        sb.AppendLine("/// Per-pass wrappers delegate to the same implementation (specialization is per-shader).");
        for (int pi = 0; pi < passCount; pi++)
        {
            sb.Append("pub fn pipeline_compilation_options_pass").Append(pi).AppendLine("_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.AppendLine("    pipeline_compilation_options_vertex_inner(variant)");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.Append("pub fn pipeline_compilation_options_pass").Append(pi).AppendLine("_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {");
            sb.AppendLine("    pipeline_compilation_options_vertex_inner(variant)");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static void EmitCreateRenderPipelineDispatcher(StringBuilder sb, int passCount)
    {
        sb.AppendLine("/// Dispatches to `create_render_pipeline_passN` by index. Panics if `pass_index` is out of range.");
        sb.AppendLine("#[allow(clippy::too_many_arguments)]");
        sb.AppendLine("pub fn create_render_pipeline(");
        sb.AppendLine("    device: &wgpu::Device,");
        sb.AppendLine("    label: &str,");
        sb.AppendLine("    layout: &wgpu::PipelineLayout,");
        sb.AppendLine("    surface_format: wgpu::TextureFormat,");
        sb.AppendLine("    depth_format: Option<wgpu::TextureFormat>,");
        sb.AppendLine("    variant: &VariantKey,");
        sb.AppendLine("    pass_index: usize,");
        sb.AppendLine("    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,");
        sb.AppendLine(") -> wgpu::RenderPipeline {");
        sb.AppendLine("    match pass_index {");
        for (int pi = 0; pi < passCount; pi++)
        {
            sb.Append("        ").Append(pi).Append(" => create_render_pipeline_pass").Append(pi).AppendLine("(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),");
        }

        sb.AppendLine("        _ => panic!(\"invalid pass_index for this shader module\"),");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static bool IsTexturePropertyKind(ShaderPropertyKind k) => MaterialUniformStd140Layout.IsTexturePropertyKind(k);

    private static void EmitMaterialUniformBlock(StringBuilder sb, IReadOnlyList<ShaderPropertyRecord> properties)
    {
        bool anyScalar = properties.Any(static p => !IsTexturePropertyKind(p.Kind));
        if (!anyScalar)
            return;

        (IReadOnlyList<Std140UniformField> fields, _) = MaterialUniformStd140Layout.Build(properties);
        sb.AppendLine("/// Uniform buffer layout matching the prepended WGSL `MaterialUniform` (std140 with explicit padding).");
        sb.AppendLine("#[repr(C, align(16))]");
        sb.AppendLine("#[allow(dead_code)]");
        sb.AppendLine("pub struct MaterialUniform {");
        foreach (Std140UniformField f in fields)
        {
            sb.Append("    pub ").Append(f.RustFieldName).Append(": ").Append(f.RustType).AppendLine(",");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitMaterialBindGroupRust(StringBuilder sb, IReadOnlyList<ShaderPropertyRecord> properties)
    {
        bool anyScalar = properties.Any(static p => !IsTexturePropertyKind(p.Kind));
        sb.AppendLine("/// Bind group 1: `MaterialUniform` at binding 0, then each texture + sampler pair.");
        sb.AppendLine("fn push_material_bind_group_layout_entries(entries: &mut Vec<wgpu::BindGroupLayoutEntry>) {");
        if (anyScalar)
        {
            sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
            sb.AppendLine("        binding: 0,");
            sb.AppendLine("        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,");
            sb.AppendLine("        ty: wgpu::BindingType::Buffer {");
            sb.AppendLine("            ty: wgpu::BufferBindingType::Uniform,");
            sb.AppendLine("            has_dynamic_offset: false,");
            sb.AppendLine("            min_binding_size: None,");
            sb.AppendLine("        },");
            sb.AppendLine("        count: None,");
            sb.AppendLine("    });");
        }

        uint b = 1;
        foreach (ShaderPropertyRecord prop in properties)
        {
            if (!IsTexturePropertyKind(prop.Kind))
                continue;
            sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
            sb.Append("        binding: ").Append(b.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
            sb.AppendLine("        ty: wgpu::BindingType::Texture {");
            sb.AppendLine("            sample_type: wgpu::TextureSampleType::Float { filterable: true },");
            sb.Append("            view_dimension: ");
            sb.AppendLine(TextureViewDimensionRust(prop.Kind));
            sb.AppendLine("            multisampled: false,");
            sb.AppendLine("        },");
            sb.AppendLine("        count: None,");
            sb.AppendLine("    });");
            b++;
            sb.AppendLine("    entries.push(wgpu::BindGroupLayoutEntry {");
            sb.Append("        binding: ").Append(b.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            sb.AppendLine("        visibility: wgpu::ShaderStages::FRAGMENT,");
            sb.AppendLine("        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),");
            sb.AppendLine("        count: None,");
            sb.AppendLine("    });");
            b++;
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("pub fn create_material_bind_group_layout(device: &wgpu::Device, label: &str) -> wgpu::BindGroupLayout {");
        sb.AppendLine("    let mut entries = Vec::new();");
        sb.AppendLine("    push_material_bind_group_layout_entries(&mut entries);");
        sb.AppendLine("    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {");
        sb.AppendLine("        label: Some(label),");
        sb.AppendLine("        entries: &entries,");
        sb.AppendLine("    })");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// `texture_views_and_samplers` must contain one `(view, sampler)` per texture property in Properties order.");
        sb.AppendLine("pub fn create_material_bind_group(");
        sb.AppendLine("    device: &wgpu::Device,");
        sb.AppendLine("    layout: &wgpu::BindGroupLayout,");
        sb.AppendLine("    label: &str,");
        sb.AppendLine("    material_uniform_buffer: &wgpu::Buffer,");
        sb.AppendLine("    texture_views_and_samplers: &[(&wgpu::TextureView, &wgpu::Sampler)],");
        sb.AppendLine(") -> wgpu::BindGroup {");
        sb.AppendLine("    let mut entries: Vec<wgpu::BindGroupEntry> = Vec::new();");
        if (anyScalar)
        {
            sb.AppendLine("    entries.push(wgpu::BindGroupEntry {");
            sb.AppendLine("        binding: 0,");
            sb.AppendLine("        resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {");
            sb.AppendLine("            buffer: material_uniform_buffer,");
            sb.AppendLine("            offset: 0,");
            sb.AppendLine("            size: None,");
            sb.AppendLine("        }),");
            sb.AppendLine("    });");
        }

        sb.AppendLine("    let mut b: u32 = 1;");
        sb.AppendLine("    for (view, sampler) in texture_views_and_samplers {");
        sb.AppendLine("        entries.push(wgpu::BindGroupEntry {");
        sb.AppendLine("            binding: b,");
        sb.AppendLine("            resource: wgpu::BindingResource::TextureView(view),");
        sb.AppendLine("        });");
        sb.AppendLine("        b += 1;");
        sb.AppendLine("        entries.push(wgpu::BindGroupEntry {");
        sb.AppendLine("            binding: b,");
        sb.AppendLine("            resource: wgpu::BindingResource::Sampler(sampler),");
        sb.AppendLine("        });");
        sb.AppendLine("        b += 1;");
        sb.AppendLine("    }");
        sb.AppendLine("    device.create_bind_group(&wgpu::BindGroupDescriptor { label: Some(label), layout, entries: &entries })");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string EscapeRustString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string RustFieldName(string uniformName)
    {
        string n = uniformName.TrimStart('_');
        if (n.Length == 0)
            n = "unnamed";
        string lowered = $"{char.ToLowerInvariant(n[0])}{n.AsSpan(1)}";
        return RustEscapeIdent(lowered);
    }

    private static string RustEscapeIdent(string s)
    {
        if (s.Length > 0 && char.IsDigit(s[0]))
            return "u_" + s;
        return s;
    }

    private static string TextureViewDimensionRust(ShaderPropertyKind k) =>
        k switch
        {
            ShaderPropertyKind.TextureCube => "wgpu::TextureViewDimension::Cube,",
            ShaderPropertyKind.Texture2DArray => "wgpu::TextureViewDimension::D2Array,",
            ShaderPropertyKind.TextureCubeArray => "wgpu::TextureViewDimension::CubeArray,",
            ShaderPropertyKind.Texture3D or ShaderPropertyKind.Texture3DArray => "wgpu::TextureViewDimension::D3,",
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.TextureAny => "wgpu::TextureViewDimension::D2,",
            _ => "wgpu::TextureViewDimension::D2,",
        };

    private static string RustPropertyType(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range => "f32",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int => "i32",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector => "Vec4",
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "TextureHandle",
            _ => "()",
        };

    private static string DefaultRustValue(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range =>
                prop.DefaultSummary.Length > 0 && float.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out float f)
                    ? f.ToString(CultureInfo.InvariantCulture)
                    : "0.0",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int =>
                prop.DefaultSummary.Length > 0 && int.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out int i)
                    ? i.ToString(CultureInfo.InvariantCulture)
                    : "0",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector =>
                ParseVec4Default(prop.DefaultSummary),
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "0",
            _ => "()",
        };

    private static string ParseVec4Default(string summary)
    {
        ReadOnlySpan<char> s = summary.AsSpan().Trim();
        if (s.Length < 5 || s[0] != '(')
            return "Vec4::ONE";
        s = s[1..^1];
        var parts = new List<float>();
        foreach (string part in s.ToString().Split(','))
        {
            if (float.TryParse(part.Trim(), CultureInfo.InvariantCulture, out float v))
                parts.Add(v);
        }

        if (parts.Count >= 4)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, {F32Lit(parts[3])})";
        if (parts.Count == 3)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, 1.0)";
        return "Vec4::ONE";
    }

    private static string F32Lit(float x)
    {
        string s = x.ToString("G9", CultureInfo.InvariantCulture);
        if (!s.Contains('.') && !s.Contains('E') && !s.Contains('e'))
            s += ".0";
        return s;
    }

    private static string EscapeComment(string s) => s.Replace("*/", "* /");
}
