using System.Text;
using System.Text.RegularExpressions;

namespace UnityShaderConverter.Emission;

/// <summary>Root <c>shaders/mod.rs</c> merge helpers for <see cref="RustEmitter"/>.</summary>
public static partial class RustEmitter
{
    /// <summary>
    /// Extracts Rust module names from <c>pub mod name;</c> lines inside the UnityShaderConverter-generated section of <paramref name="existingRootModRs"/>.
    /// </summary>
    /// <returns>Names in file order; empty when markers are missing.</returns>
    public static IReadOnlyList<string> ListConverterGeneratedModNamesInExistingRoot(string? existingRootModRs)
    {
        if (string.IsNullOrEmpty(existingRootModRs))
            return Array.Empty<string>();

        int start = existingRootModRs.IndexOf("// GENERATED BY UnityShaderConverter", StringComparison.Ordinal);
        if (start < 0)
            return Array.Empty<string>();

        int end = existingRootModRs.IndexOf(ShadersRootGeneratedEndMarker, start, StringComparison.Ordinal);
        if (end < 0)
            return Array.Empty<string>();

        string section = existingRootModRs[start..end];
        var names = new List<string>();
        foreach (Match m in GeneratedPubModRegex().Matches(section))
        {
            if (m.Groups.Count > 1)
                names.Add(m.Groups[1].Value);
        }

        return names;
    }

    [GeneratedRegex(@"^\s*pub\s+mod\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*;\s*$", RegexOptions.Multiline)]
    private static partial Regex GeneratedPubModRegex();

    /// <summary>Merges sorted <c>pub mod &lt;shader_stem&gt;;</c> lines into the crate <c>shaders/mod.rs</c>, preserving the tail below the end marker.</summary>
    /// <param name="existingRootModRs">Current file text, or <c>null</c> if missing.</param>
    /// <param name="successModNames">Rust module names written successfully this run.</param>
    /// <param name="preservedFailedModNames">Module names that failed this run but must stay declared (and protected from stale cleanup).</param>
    public static string MergeShadersRootModRs(
        string? existingRootModRs,
        IReadOnlyList<string> successModNames,
        IReadOnlyList<string>? preservedFailedModNames = null)
    {
        var union = new HashSet<string>(StringComparer.Ordinal);
        foreach (string s in successModNames)
            union.Add(s);
        foreach (string s in preservedFailedModNames ?? Array.Empty<string>())
            union.Add(s);
        foreach (string s in ListConverterGeneratedModNamesInExistingRoot(existingRootModRs))
            union.Add(s);

        var merged = union.ToList();
        merged.Sort(StringComparer.Ordinal);
        string block = BuildShadersRootGeneratedBlock(merged);

        if (string.IsNullOrEmpty(existingRootModRs))
        {
            return "//! UnityShaderConverter emits one subdirectory per shader here (e.g. `pbs_metallic/material.rs`).\n"
                + "//! Add hand-written shader modules below the end marker to avoid merge conflicts.\n\n"
                + block;
        }

        string text = existingRootModRs;
        int markerIdx = text.IndexOf(ShadersRootGeneratedEndMarker, StringComparison.Ordinal);
        string tail;
        int docSearchLimit = text.Length;
        if (markerIdx >= 0)
        {
            int tailStart = markerIdx + ShadersRootGeneratedEndMarker.Length;
            tail = tailStart < text.Length ? text[tailStart..].TrimStart('\r', '\n') : "";
            docSearchLimit = markerIdx;
        }
        else
        {
            int cfgTest = text.IndexOf("#[cfg(test)]", StringComparison.Ordinal);
            if (cfgTest >= 0)
            {
                tail = text[cfgTest..].TrimStart('\r', '\n');
                docSearchLimit = cfgTest;
            }
            else
                tail = "";
        }

        string headDoc = ExtractLeadingModuleDocs(text, docSearchLimit);
        if (headDoc.Length == 0)
        {
            headDoc = "//! UnityShaderConverter emits one subdirectory per shader in this module. Hand-written modules go below the end marker.\n";
        }

        string tailOut = tail.Length > 0 ? "\n" + tail.TrimStart() + (tail.TrimEnd().EndsWith('\n') ? "" : "\n") : "\n";
        return headDoc.TrimEnd() + "\n\n" + block + tailOut;
    }

    /// <summary>Builds the marker-delimited block: header comment, one <c>pub mod</c> per name (sorted, distinct), then the end marker.</summary>
    private static string BuildShadersRootGeneratedBlock(IReadOnlyList<string> converterShaderModNames)
    {
        var names = new List<string>(converterShaderModNames.Distinct(StringComparer.Ordinal));
        names.Sort(StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// GENERATED BY UnityShaderConverter — do not edit between this line and the end marker.");
        foreach (string m in names)
            sb.Append("pub mod ").Append(m).AppendLine(";");
        sb.AppendLine(ShadersRootGeneratedEndMarker);
        return sb.ToString();
    }

    private static string ExtractLeadingModuleDocs(string text, int searchLimit)
    {
        int limit = Math.Min(searchLimit, text.Length);
        var lines = text.AsSpan(0, limit).ToString().Split('\n');
        var doc = new StringBuilder();
        int i = 0;
        while (i < lines.Length)
        {
            string line = lines[i].TrimEnd('\r');
            string t = line.TrimStart();
            if (t.StartsWith("//!", StringComparison.Ordinal))
            {
                doc.AppendLine(line);
                i++;
                continue;
            }

            if (string.IsNullOrWhiteSpace(line))
            {
                if (doc.Length > 0)
                    doc.AppendLine();
                i++;
                continue;
            }

            break;
        }

        return doc.ToString().TrimEnd();
    }
}
