using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using UnityShaderConverter.Analysis;
using UnityShaderConverter.Variants;

namespace UnityShaderConverter.Emission;

/// <summary>Emits a single <c>.slang</c> translation unit for one pass.</summary>
public static class SlangEmitter
{
    /// <summary>Name of the include inserted after the shader’s initial <c>#include</c> block to fix Slang token pasting for <c>sampler##_Tex</c> (see file comments).</summary>
    internal const string UnityCompatPostUnityIncludeFileName = "UnityCompatPostUnity.slang";

    private static readonly Regex LegacySampler2DDeclRegex = new(
        @"^(?<indent>\s*)sampler2D\s+(?<name>_[A-Za-z0-9]+|[A-Za-z][A-Za-z0-9]*)\s*;\s*$",
        RegexOptions.Multiline | RegexOptions.CultureInvariant,
        TimeSpan.FromSeconds(1));

    private static readonly Regex LegacySampler3DDeclRegex = new(
        @"^(?<indent>\s*)sampler3D\s+(?<name>_[A-Za-z0-9]+|[A-Za-z][A-Za-z0-9]*)\s*;\s*$",
        RegexOptions.Multiline | RegexOptions.CultureInvariant,
        TimeSpan.FromSeconds(1));

    private static readonly Regex LegacySamplerCubeDeclRegex = new(
        @"^(?<indent>\s*)samplerCUBE\s+(?<name>_[A-Za-z0-9]+|[A-Za-z][A-Za-z0-9]*)\s*;\s*$",
        RegexOptions.Multiline | RegexOptions.CultureInvariant,
        TimeSpan.FromSeconds(1));

    /// <summary>
    /// <c>appdata_full.texcoord</c> is often <c>float4</c> while <c>v2f.uv</c> is <c>float2</c>; Slang rejects the assignment without a swizzle.
    /// </summary>
    private static readonly Regex Float4TexcoordToUvRegex = new(
        @"(\w+)\.uv\s*=\s*(\w+)\.texcoord(?!\s*\.\s*xy)\s*;",
        RegexOptions.CultureInvariant,
        TimeSpan.FromSeconds(1));

    /// <summary>
    /// Builds Slang with Unity compat and optional <c>[vk::constant_id]</c> specialization bools. Baseline variant keywords are supplied only via <c>slangc -D</c> (no duplicate <c>#define</c> in source).
    /// </summary>
    /// <param name="baselineDefines">Preprocessor symbols for this pass; emitted only through <c>slangc -D</c>, not as <c>#define</c> lines.</param>
    public static string EmitPassSlang(
        ShaderPassDocument pass,
        IReadOnlyList<string> baselineDefines,
        IReadOnlyList<SpecializationAxis> specializationAxes)
    {
        ArgumentNullException.ThrowIfNull(baselineDefines);
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by UnityShaderConverter — do not edit.");
        sb.AppendLine("#include \"UnityCompat.slang\"");
        sb.AppendLine();
        foreach (SpecializationAxis axis in specializationAxes)
        {
            sb.Append("[vk::constant_id(").Append(axis.ConstantId).Append(")] const bool ")
                .Append(axis.SlangIdentifier).AppendLine(" = false;");
        }

        if (specializationAxes.Count > 0)
            sb.AppendLine();

        string programBody = StripCompilerDirectivesToString(pass.ProgramSource);
        if (specializationAxes.Count > 0)
        {
            var map = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (SpecializationAxis ax in specializationAxes)
                map[ax.Keyword] = ax.SlangIdentifier;
            programBody = HlslSpecializationPreprocessor.Rewrite(programBody, map);
        }

        programBody = InsertUnityCompatPostIncludeAfterInitialIncludes(programBody);
        programBody = RewriteLegacySampler2DDeclarations(programBody);
        programBody = RewriteLegacySampler3DDeclarations(programBody);
        programBody = RewriteLegacySamplerCubeDeclarations(programBody);
        programBody = RewriteFloat4TexcoordUvAssignments(programBody);

        foreach (string line in programBody.Split('\n'))
        {
            string lineOut = line.TrimEnd('\r');
            sb.AppendLine(lineOut);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Prepends <c>UnityCG.cginc</c> then <c>UnityCompatPostUnity.slang</c> so split-sampler macro overrides are active
    /// before any pass include (e.g. Resonite <c>Common.cginc</c> first) while relying on Unity include guards for duplicates.
    /// </summary>
    internal static string InsertUnityCompatPostIncludeAfterInitialIncludes(string programBody)
    {
        const string unityCgInclude = "#include \"UnityCG.cginc\"";
        string postUnity = $"#include \"{UnityCompatPostUnityIncludeFileName}\"";
        if (string.IsNullOrEmpty(programBody))
            return $"{unityCgInclude}\n{postUnity}";

        return $"{unityCgInclude}\n{postUnity}\n{programBody}";
    }

    /// <summary>
    /// Maps legacy <c>sampler2D _Tex;</c> / <c>sampler2D Name;</c> declarations to <c>UNITY_DECLARE_TEX2D</c> so split samplers exist for <c>tex2D</c>.
    /// </summary>
    internal static string RewriteLegacySampler2DDeclarations(string programBody) =>
        LegacySampler2DDeclRegex.Replace(
            programBody,
            m => $"{m.Groups["indent"].Value}UNITY_DECLARE_TEX2D({m.Groups["name"].Value});");

    /// <summary>
    /// Maps legacy <c>sampler3D _Vol;</c> to <c>UNITY_DECLARE_TEX3D</c> so <c>tex3D</c> has a paired <c>SamplerState</c>.
    /// </summary>
    internal static string RewriteLegacySampler3DDeclarations(string programBody) =>
        LegacySampler3DDeclRegex.Replace(
            programBody,
            m => $"{m.Groups["indent"].Value}UNITY_DECLARE_TEX3D({m.Groups["name"].Value});");

    /// <summary>
    /// Maps legacy <c>samplerCUBE _Cube;</c> to <c>UNITY_DECLARE_TEXCUBE</c> so <c>texCUBE</c> resolves <c>SamplerState sampler_Name</c> (e.g. <c>sampler_Cube</c> for <c>_Cube</c>).
    /// </summary>
    internal static string RewriteLegacySamplerCubeDeclarations(string programBody) =>
        LegacySamplerCubeDeclRegex.Replace(
            programBody,
            m => $"{m.Groups["indent"].Value}UNITY_DECLARE_TEXCUBE({m.Groups["name"].Value});");

    /// <summary>
    /// Rewrites <c>o.uv = v.texcoord;</c>-style assignments so the RHS uses <c>.xy</c> when not already swizzled.
    /// </summary>
    internal static string RewriteFloat4TexcoordUvAssignments(string programBody) =>
        Float4TexcoordToUvRegex.Replace(
            programBody,
            m => $"{m.Groups[1].Value}.uv = {m.Groups[2].Value}.texcoord.xy;");

    private static string StripCompilerDirectivesToString(string program)
    {
        var sb = new StringBuilder();
        foreach (string rawLine in program.Split('\n'))
        {
            string line = rawLine.TrimEnd('\r');
            string t = line.TrimStart();
            if (t.StartsWith("#pragma", StringComparison.Ordinal))
                continue;
            sb.AppendLine(line);
        }

        return sb.ToString().TrimEnd();
    }
}
