using System.Linq;
using System.Text;
using UnityShaderConverter.Analysis;
using UnityShaderConverter.Variants;

namespace UnityShaderConverter.Emission;

/// <summary>Emits a single <c>.slang</c> translation unit for one pass.</summary>
public static class SlangEmitter
{
    /// <summary>Builds Slang with Unity compat, optional <c>[vk::constant_id]</c> specialization bools, and baseline <c>#define</c>s.</summary>
    public static string EmitPassSlang(
        ShaderPassDocument pass,
        IReadOnlyList<string> baselineDefines,
        IReadOnlyList<SpecializationAxis> specializationAxes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by UnityShaderConverter — do not edit.");
        sb.AppendLine("#include \"UnityCompat.slang\"");
        sb.AppendLine();
        foreach (SpecializationAxis axis in specializationAxes)
        {
            sb.Append("[vk::constant_id(").Append(axis.ConstantId).Append(")] const bool ")
                .Append(axis.SlangIdentifier).AppendLine(" = false;");
        }

        if (specializationAxes.Count > 0)
            sb.AppendLine();

        foreach (string d in baselineDefines)
        {
            if (d.Length > 0)
                sb.Append("#define ").AppendLine(d);
        }

        if (baselineDefines.Any(static s => s.Length > 0))
            sb.AppendLine();

        foreach (string line in StripCompilerDirectives(pass.ProgramSource))
            sb.AppendLine(line);

        return sb.ToString();
    }

    private static IEnumerable<string> StripCompilerDirectives(string program)
    {
        foreach (string rawLine in program.Split('\n'))
        {
            string line = rawLine.TrimEnd('\r');
            string t = line.TrimStart();
            if (t.StartsWith("#pragma", StringComparison.Ordinal))
                continue;
            yield return line;
        }
    }
}
