using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityShaderConverter.Analysis;
using UnityShaderConverter.Variants;

namespace UnityShaderConverter.Emission;

/// <summary>Emits a single <c>.slang</c> translation unit for one pass.</summary>
public static class SlangEmitter
{
    /// <summary>Name of the include inserted after the shader’s initial <c>#include</c> block to fix Slang token pasting for <c>sampler##_Tex</c> (see file comments).</summary>
    internal const string UnityCompatPostUnityIncludeFileName = "UnityCompatPostUnity.slang";

    private static readonly Regex LegacySampler2DDeclRegex = new(
        @"^(?<indent>\s*)sampler2D\s+(?<name>_[A-Za-z0-9]+)\s*;\s*$",
        RegexOptions.Multiline | RegexOptions.CultureInvariant,
        TimeSpan.FromSeconds(1));

    /// <summary>
    /// Builds Slang with Unity compat and optional <c>[vk::constant_id]</c> specialization bools. Baseline variant keywords are supplied only via <c>slangc -D</c> (no duplicate <c>#define</c> in source).
    /// </summary>
    /// <param name="baselineDefines">Preprocessor symbols for this pass; emitted only through <c>slangc -D</c>, not as <c>#define</c> lines.</param>
    public static string EmitPassSlang(
        ShaderPassDocument pass,
        IReadOnlyList<string> baselineDefines,
        IReadOnlyList<SpecializationAxis> specializationAxes)
    {
        ArgumentNullException.ThrowIfNull(baselineDefines);
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by UnityShaderConverter — do not edit.");
        sb.AppendLine("#include \"UnityCompat.slang\"");
        sb.AppendLine();
        foreach (SpecializationAxis axis in specializationAxes)
        {
            sb.Append("[vk::constant_id(").Append(axis.ConstantId).Append(")] const bool ")
                .Append(axis.SlangIdentifier).AppendLine(" = false;");
        }

        if (specializationAxes.Count > 0)
            sb.AppendLine();

        string programBody = StripCompilerDirectivesToString(pass.ProgramSource);
        if (specializationAxes.Count > 0)
        {
            var map = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (SpecializationAxis ax in specializationAxes)
                map[ax.Keyword] = ax.SlangIdentifier;
            programBody = HlslSpecializationPreprocessor.Rewrite(programBody, map);
        }

        programBody = InsertUnityCompatPostIncludeAfterInitialIncludes(programBody);
        programBody = RewriteLegacySampler2DDeclarations(programBody);

        foreach (string line in programBody.Split('\n'))
        {
            string lineOut = line.TrimEnd('\r');
            sb.AppendLine(lineOut);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Inserts <c>#include "UnityCompatPostUnity.slang"</c> after the first run of <c>#include</c> lines (and blank lines), or at the start if there are none.
    /// </summary>
    internal static string InsertUnityCompatPostIncludeAfterInitialIncludes(string programBody)
    {
        if (string.IsNullOrEmpty(programBody))
            return $"#include \"{UnityCompatPostUnityIncludeFileName}\"";

        string[] rawLines = programBody.Split('\n');
        int insertAt = 0;
        for (; insertAt < rawLines.Length; insertAt++)
        {
            string line = rawLines[insertAt];
            string t = line.TrimStart();
            if (t.StartsWith("#include", StringComparison.Ordinal))
                continue;
            if (string.IsNullOrWhiteSpace(line))
                continue;
            break;
        }

        var lines = new List<string>(rawLines.Length + 1);
        for (int j = 0; j < insertAt; j++)
            lines.Add(rawLines[j]);
        lines.Add($"#include \"{UnityCompatPostUnityIncludeFileName}\"");
        for (int j = insertAt; j < rawLines.Length; j++)
            lines.Add(rawLines[j]);
        return string.Join("\n", lines);
    }

    /// <summary>
    /// Maps legacy <c>sampler2D _Tex;</c> declarations to <c>UNITY_DECLARE_TEX2D(_Tex);</c> so <c>tex2D</c> resolves <c>SamplerState sampler_Tex</c> after the <c>sampler2D</c> typedef.
    /// </summary>
    internal static string RewriteLegacySampler2DDeclarations(string programBody) =>
        LegacySampler2DDeclRegex.Replace(
            programBody,
            m => $"{m.Groups["indent"].Value}UNITY_DECLARE_TEX2D({m.Groups["name"].Value});");

    private static string StripCompilerDirectivesToString(string program)
    {
        var sb = new StringBuilder();
        foreach (string rawLine in program.Split('\n'))
        {
            string line = rawLine.TrimEnd('\r');
            string t = line.TrimStart();
            if (t.StartsWith("#pragma", StringComparison.Ordinal))
                continue;
            sb.AppendLine(line);
        }

        return sb.ToString().TrimEnd();
    }
}
