using NotEnoughLogs;
using NotEnoughLogs.Behaviour;

namespace UnityShaderConverter.Tests;

/// <summary>Tests for <see cref="ConverterRunner.RemoveStaleConverterShaderDirectories"/> when some modules are only preserved, not successfully regenerated.</summary>
public sealed class ConverterRunnerStaleTests
{
    [Fact]
    public void RemoveStaleConverterShaderDirectories_KeepsDirsWhoseNamesArePreserved()
    {
        using var logger = new Logger(new LoggerConfiguration
        {
            Behaviour = new DirectLoggingBehaviour(),
            MaxLevel = LogLevel.Trace,
        });

        string root = Path.Combine(Path.GetTempPath(), "UnityShaderConverterStaleTests", Guid.NewGuid().ToString("N"));
        try
        {
            string keep = Path.Combine(root, "keep_me");
            string remove = Path.Combine(root, "orphan_mod");
            Directory.CreateDirectory(keep);
            Directory.CreateDirectory(remove);
            File.WriteAllText(
                Path.Combine(keep, "mod.rs"),
                "//! @generated by UnityShaderConverter — do not edit.\n");
            File.WriteAllText(
                Path.Combine(remove, "mod.rs"),
                "//! @generated by UnityShaderConverter — do not edit.\n");

            var preserved = new HashSet<string>(StringComparer.Ordinal) { "keep_me" };
            ConverterRunner.RemoveStaleConverterShaderDirectories(root, preserved, logger);

            Assert.True(Directory.Exists(keep));
            Assert.False(Directory.Exists(remove));
        }
        finally
        {
            try
            {
                if (Directory.Exists(root))
                    Directory.Delete(root, recursive: true);
            }
            catch
            {
                // ignored
            }
        }
    }

    [Fact]
    public void RemoveStaleConverterShaderDirectories_KeepsFailedModWhenInPreservedSet()
    {
        using var logger = new Logger(new LoggerConfiguration
        {
            Behaviour = new DirectLoggingBehaviour(),
            MaxLevel = LogLevel.Trace,
        });

        string root = Path.Combine(Path.GetTempPath(), "UnityShaderConverterStaleTests", Guid.NewGuid().ToString("N"));
        try
        {
            string failed = Path.Combine(root, "failed_shader_mod");
            Directory.CreateDirectory(failed);
            File.WriteAllText(
                Path.Combine(failed, "mod.rs"),
                "//! @generated by UnityShaderConverter — do not edit.\n");

            var preserved = new HashSet<string>(StringComparer.Ordinal) { "failed_shader_mod" };
            ConverterRunner.RemoveStaleConverterShaderDirectories(root, preserved, logger);

            Assert.True(Directory.Exists(failed));
        }
        finally
        {
            try
            {
                if (Directory.Exists(root))
                    Directory.Delete(root, recursive: true);
            }
            catch
            {
                // ignored
            }
        }
    }
}
