using UnityShaderConverter.Emission;

namespace UnityShaderConverter.Tests;

/// <summary>Tests for <see cref="RustEmitter"/> root <c>mod.rs</c> merging.</summary>
public sealed class RustEmitterTests
{
    [Fact]
    public void MergeShadersRootModRs_NullExisting_EmitsSortedDistinctMods()
    {
        string merged = RustEmitter.MergeShadersRootModRs(
            null,
            new[] { "zebra", "alpha", "alpha" });

        Assert.Contains("pub mod alpha;", merged, StringComparison.Ordinal);
        Assert.Contains("pub mod zebra;", merged, StringComparison.Ordinal);
        int alphaIdx = merged.IndexOf("pub mod alpha;", StringComparison.Ordinal);
        int zebraIdx = merged.IndexOf("pub mod zebra;", StringComparison.Ordinal);
        Assert.True(alphaIdx >= 0 && zebraIdx > alphaIdx);
        Assert.DoesNotContain("pub mod generated;", merged, StringComparison.Ordinal);
    }

    [Fact]
    public void MergeShadersRootModRs_PreservesTailBelowMarker()
    {
        const string existing = """
            //! doc

            // GENERATED BY UnityShaderConverter — do not edit between this line and the end marker.
            pub mod old;
            // --- END UNITY_SHADER_CONVERTER_GENERATED ---

            #[cfg(test)]
            mod t {}
            """;

        string merged = RustEmitter.MergeShadersRootModRs(
            existing,
            new[] { "foo" });

        Assert.Contains("pub mod foo;", merged, StringComparison.Ordinal);
        Assert.Contains("pub mod old;", merged, StringComparison.Ordinal);
        Assert.Contains("#[cfg(test)]", merged, StringComparison.Ordinal);
        Assert.Contains("mod t {}", merged, StringComparison.Ordinal);
    }

    [Fact]
    public void MergeShadersRootModRs_UnionsSuccessPreservedFailedAndExistingGeneratedMods()
    {
        const string existing = """
            // GENERATED BY UnityShaderConverter — do not edit between this line and the end marker.
            pub mod from_existing;
            // --- END UNITY_SHADER_CONVERTER_GENERATED ---
            """;

        string merged = RustEmitter.MergeShadersRootModRs(
            existing,
            successModNames: new[] { "success_only" },
            preservedFailedModNames: new[] { "failed_keep" });

        Assert.Contains("pub mod failed_keep;", merged, StringComparison.Ordinal);
        Assert.Contains("pub mod from_existing;", merged, StringComparison.Ordinal);
        Assert.Contains("pub mod success_only;", merged, StringComparison.Ordinal);
    }

    [Fact]
    public void ListConverterGeneratedModNamesInExistingRoot_ParsesGeneratedSection()
    {
        const string existing = """
            // GENERATED BY UnityShaderConverter — do not edit between this line and the end marker.
            pub mod a;
            pub mod z_bracket;
            // --- END UNITY_SHADER_CONVERTER_GENERATED ---
            """;

        IReadOnlyList<string> names = RustEmitter.ListConverterGeneratedModNamesInExistingRoot(existing);
        Assert.Equal(2, names.Count);
        Assert.Contains("a", names, StringComparer.Ordinal);
        Assert.Contains("z_bracket", names, StringComparer.Ordinal);
    }
}
