using System.Text.RegularExpressions;
using SharedTypeGenerator.Analysis;
using SharedTypeGenerator.IR;

namespace SharedTypeGenerator.Emission;

public partial class RustEmitter
{
    /// <summary>
    /// Writes the generated file header: generated notice, <c>#![allow(...)]</c> (including
    /// <c>missing_docs</c> and <c>clippy::large_enum_variant</c>), a minimal <c>glam</c> import list,
    /// and shared imports.
    /// </summary>
    private void EmitHeader(List<TypeDescriptor> types)
    {
        _w.Comment("This file is automatically generated by SharedTypeGenerator. Please do not modify this file.");
        _w.Comment($"Generated for {_engineVersion}\n");
        _w.Line("#![allow(");
        _w.Line("    missing_docs,");
        _w.Line("    clippy::large_enum_variant,");
        _w.Line(")]");
        _w.BlankLine();
        string glamList = FormatGlamUseList(types);
        _w.Line($"use glam::{{{glamList}}};");
        _w.Line("use super::packing::memory_packable::MemoryPackable;");
        _w.Line("use super::packing::memory_packer::MemoryPacker;");
        _w.Line("use super::packing::memory_unpacker::MemoryUnpacker;");
        _w.Line("use super::packing::memory_packer_entity_pool::MemoryPackerEntityPool;");
        _w.Line("use super::packing::polymorphic_memory_packable_entity::PolymorphicEncode;");
        _w.Line("use super::buffer::SharedMemoryBufferDescriptor;");
        _w.Line("use super::packing::enum_repr::EnumRepr;");
        _w.Line("use bytemuck::{Pod, Zeroable};");
        _w.Line("use logger::warn;");
        _w.BlankLine();
    }

    /// <summary>Comma-separated <c>glam</c> identifiers for <c>use glam::{{ ... }};</c>, stable order.</summary>
    private static string FormatGlamUseList(List<TypeDescriptor> types)
    {
        List<string> names = CollectRequiredGlamTypeNames(types);
        if (names.Count == 0)
            return string.Join(", ", GlamImportOrder);
        return string.Join(", ", names);
    }

    /// <summary>Collects which <c>glam::*</c> primitive names appear in field and polymorphic payload Rust type strings.</summary>
    private static List<string> CollectRequiredGlamTypeNames(List<TypeDescriptor> types)
    {
        var set = new HashSet<string>();
        foreach (TypeDescriptor t in types)
        {
            foreach (FieldDescriptor f in t.Fields)
                AddGlamTokensFromRustType(f.RustType, set);

            if (t.Variants != null)
            {
                foreach (PolymorphicVariant v in t.Variants)
                    AddGlamTokensFromRustType(v.CSharpName.HumanizeType(), set);
            }
        }

        List<string> ordered = [];
        foreach (string name in GlamImportOrder)
        {
            if (set.Contains(name))
                ordered.Add(name);
        }

        return ordered;
    }

    private static void AddGlamTokensFromRustType(string rustType, HashSet<string> set)
    {
        if (string.IsNullOrEmpty(rustType))
            return;

        foreach (string token in Regex.Split(rustType, @"[^A-Za-z0-9_]+"))
        {
            if (token.Length == 0)
                continue;
            if (GlamImportOrder.Contains(token))
                set.Add(token);
        }
    }
}
