using System.Linq;
using System.Text.RegularExpressions;
using NotEnoughLogs;
using SharedTypeGenerator.Analysis;
using SharedTypeGenerator.IR;
using SharedTypeGenerator.Logging;

namespace SharedTypeGenerator.Emission;

/// <summary>Backend orchestrator: takes a list of TypeDescriptors and emits the complete
/// shared.rs file. Dispatches each type to shape-specific emission methods.
/// No reflection, no Cecil -- purely data-driven from the IR.</summary>
public class RustEmitter
{
    /// <summary>Stable order for <c>use glam::{{ ... }};</c>; only names referenced in emitted Rust types are imported.</summary>
    private static readonly string[] GlamImportOrder =
    [
        "IVec2", "IVec3", "IVec4",
        "Mat4", "Quat",
        "Vec2", "Vec3", "Vec4",
    ];

    private readonly RustWriter _w;
    private readonly Logger _logger;
    private readonly string _engineVersion;
    private readonly bool _ilVerbose;

    /// <summary>Creates an emitter targeting <paramref name="writer"/>.</summary>
    /// <param name="logger">Receives warnings when emission is incomplete or emits FIXME-equivalent Rust.</param>
    /// <param name="ilVerbose">When true, emits leading comments naming each C# type before its Rust definition.</param>
    public RustEmitter(RustWriter writer, Logger logger, string engineVersion, bool ilVerbose = false)
    {
        _w = writer;
        _logger = logger;
        _engineVersion = engineVersion;
        _ilVerbose = ilVerbose;
    }

    /// <summary>Emits the complete shared.rs file from the analyzed type list.</summary>
    public void Emit(List<TypeDescriptor> types)
    {
        EmitHeader(types);

        foreach (TypeDescriptor type in types)
        {
            EmitType(type);
            _w.BlankLine();
        }

        EmitRoundtripDispatch(types);
    }

    /// <summary>
    /// Writes the generated file header: generated notice, <c>#![allow(...)]</c> (including
    /// <c>missing_docs</c> and <c>clippy::large_enum_variant</c>), a minimal <c>glam</c> import list,
    /// and shared imports.
    /// </summary>
    private void EmitHeader(List<TypeDescriptor> types)
    {
        _w.Comment("This file is automatically generated by SharedTypeGenerator. Please do not modify this file.");
        _w.Comment($"Generated for {_engineVersion}\n");
        _w.Line("#![allow(");
        _w.Line("    missing_docs,");
        _w.Line("    clippy::large_enum_variant,");
        _w.Line(")]");
        _w.BlankLine();
        string glamList = FormatGlamUseList(types);
        _w.Line($"use glam::{{{glamList}}};");
        _w.Line("use super::packing::memory_packable::MemoryPackable;");
        _w.Line("use super::packing::memory_packer::MemoryPacker;");
        _w.Line("use super::packing::memory_unpacker::MemoryUnpacker;");
        _w.Line("use super::packing::memory_packer_entity_pool::MemoryPackerEntityPool;");
        _w.Line("use super::packing::polymorphic_memory_packable_entity::PolymorphicEncode;");
        _w.Line("use super::buffer::SharedMemoryBufferDescriptor;");
        _w.Line("use super::packing::enum_repr::EnumRepr;");
        _w.Line("use bytemuck::{Pod, Zeroable};");
        _w.Line("use logger::warn;");
        _w.BlankLine();
    }

    /// <summary>Comma-separated <c>glam</c> identifiers for <c>use glam::{{ ... }};</c>, stable order.</summary>
    private static string FormatGlamUseList(List<TypeDescriptor> types)
    {
        List<string> names = CollectRequiredGlamTypeNames(types);
        if (names.Count == 0)
            return string.Join(", ", GlamImportOrder);
        return string.Join(", ", names);
    }

    /// <summary>Collects which <c>glam::*</c> primitive names appear in field and polymorphic payload Rust type strings.</summary>
    private static List<string> CollectRequiredGlamTypeNames(List<TypeDescriptor> types)
    {
        var set = new HashSet<string>();
        foreach (TypeDescriptor t in types)
        {
            foreach (FieldDescriptor f in t.Fields)
                AddGlamTokensFromRustType(f.RustType, set);

            if (t.Variants != null)
            {
                foreach (PolymorphicVariant v in t.Variants)
                    AddGlamTokensFromRustType(v.CSharpName.HumanizeType(), set);
            }
        }

        List<string> ordered = [];
        foreach (string name in GlamImportOrder)
        {
            if (set.Contains(name))
                ordered.Add(name);
        }

        return ordered;
    }

    private static void AddGlamTokensFromRustType(string rustType, HashSet<string> set)
    {
        if (string.IsNullOrEmpty(rustType))
            return;

        foreach (string token in Regex.Split(rustType, @"[^A-Za-z0-9_]+"))
        {
            if (token.Length == 0)
                continue;
            if (GlamImportOrder.Contains(token))
                set.Add(token);
        }
    }

    private void EmitType(TypeDescriptor type)
    {
        if (_ilVerbose)
            _w.Comment($"IL-verbose: C# {type.CSharpName} ({type.Shape})");

        switch (type.Shape)
        {
            case TypeShape.PolymorphicBase:
                EmitPolymorphic(type);
                break;
            case TypeShape.ValueEnum:
                EmitValueEnum(type);
                break;
            case TypeShape.FlagsEnum:
                EmitFlagsEnum(type);
                break;
            case TypeShape.PodStruct:
                EmitPodStruct(type);
                break;
            case TypeShape.PackableStruct:
                EmitPackableStruct(type);
                break;
            case TypeShape.GeneralStruct:
                EmitGeneralStruct(type);
                break;
        }
    }

    // ── Polymorphic ──────────────────────────────────────────────

    private void EmitPolymorphic(TypeDescriptor type)
    {
        if (type.Variants == null || type.Variants.Count == 0)
        {
            _logger.LogWarning(
                LogCategory.Fixme,
                $"Skipping polymorphic base {type.CSharpName}: no variants in IR (check PolymorphicAnalyzer / inheritance graph).");
            return;
        }

        string unionName = type.RustName;
        var typeNames = type.Variants.Select(v => v.CSharpName).ToList();

        // Discriminant enum: {Name}Types
        using (_w.BeginEnum($"{type.CSharpName}Types", "i32"))
        {
            bool first = true;
            foreach (string name in typeNames)
            {
                _w.EnumMember(name, isDefault: first);
                first = false;
            }
        }

        // Tagged union enum (Clone needed when used in Option/Vec; no Default - variants have payloads)
        using (_w.BeginUnion(type.CSharpName, "Clone"))
        {
            foreach (string name in typeNames)
                _w.EnumVariantWithPayload(name, name);
        }

        // PolymorphicEncode impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("PolymorphicEncode", unionName))
        {
            using (_w.BeginMethod("encode", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
            {
                _w.Line("match self {");
                for (int i = 0; i < typeNames.Count; i++)
                {
                    string variant = typeNames[i].HumanizeVariant();
                    _w.Line($"    {unionName}::{variant}(x) => {{ packer.write(&{i}i32); x.pack(packer); }}");
                }
                _w.Line("}");
            }
        }

        // decode function
        string decodeFnName = "decode_" + unionName.HumanizeField();
        _w.BlankLine();
        using (_w.BeginMethod(decodeFnName, unionName, ["P: MemoryPackerEntityPool"], ["unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: true))
        {
            _w.Line("let tag = unpacker.read::<i32>();");
            _w.Line("match tag {");
            for (int i = 0; i < typeNames.Count; i++)
            {
                string variant = typeNames[i].HumanizeVariant();
                string payloadType = typeNames[i].HumanizeType();
                _w.Line($"    {i} => {unionName}::{variant}({{ let mut x = {payloadType}::default(); x.unpack(unpacker); x }}),");
            }
            _w.Line("    _ => panic!(\"Invalid polymorphic tag: {:?}\", tag),");
            _w.Line("}");
        }
    }

    // ── Value Enum ───────────────────────────────────────────────

    private void EmitValueEnum(TypeDescriptor type)
    {
        if (type.EnumMembers == null || type.RustUnderlyingType == null)
        {
            _logger.LogWarning(
                LogCategory.Fixme,
                $"Skipping value enum {type.CSharpName}: missing EnumMembers or RustUnderlyingType in IR.");
            return;
        }

        string rustType = type.RustUnderlyingType;
        string name = type.RustName;

        // Enums used as keys or in comparisons need PartialEq
        using (_w.BeginEnum(name, rustType, "PartialEq"))
        {
            foreach (EnumMember member in type.EnumMembers)
                _w.EnumMemberWithValue(member.Name, member.Value.ToString()!, isDefault: member.IsDefault);
        }

        // MemoryPackable impl — decode without transmute: invalid host values must not panic (Rust 1.94+
        // treats invalid `repr` enum bit patterns as immediate UB/panic on transmute).
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                _w.Line($"packer.write(&(*self as {rustType}));");
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                EmitValueEnumUnpackMatch(name, rustType, type.EnumMembers);
        }

        // EnumRepr impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("EnumRepr", name))
        {
            using (_w.BeginMethod("as_i32", "i32", null, ["self"], isPublic: false))
                _w.Line("self as i32");
            using (_w.BeginMethod("from_i32", "Self", null, ["i: i32"], isPublic: false))
                EmitValueEnumFromI32Match(name, type.EnumMembers);
        }

        _w.BlankLine();
        _w.Line($"unsafe impl Pod for {name} {{}}");
        _w.Line($"unsafe impl Zeroable for {name} {{}}");
    }

    /// <summary>Emits <c>*self = match raw { ... }</c> for value enum wire decode.</summary>
    private void EmitValueEnumUnpackMatch(string enumRustName, string rustType, List<EnumMember> members)
    {
        EnumMember defaultMember = members.First(static m => m.IsDefault);
        string defaultVariant = defaultMember.Name.HumanizeVariant();

        _w.Line($"let raw = unpacker.read::<{rustType}>();");
        _w.Line("*self = match raw {");
        foreach (EnumMember member in members)
        {
            string lit = FormatRustPatternLiteralForUnderlying(member.Value, rustType);
            _w.Line($"    {lit} => Self::{member.Name.HumanizeVariant()},");
        }

        _w.Line("    _ => {");
        _w.Line(
            $"        warn!(\"invalid {enumRustName} wire value {{}}; using default\", raw);");
        _w.Line($"        Self::{defaultVariant}");
        _w.Line("    }");
        _w.Line("};");
    }

    /// <summary>Emits <c>match i { ... }</c> for <see cref="EnumRepr"/> without transmute.</summary>
    private void EmitValueEnumFromI32Match(string enumRustName, List<EnumMember> members)
    {
        EnumMember defaultMember = members.First(static m => m.IsDefault);
        string defaultVariant = defaultMember.Name.HumanizeVariant();

        _w.Line("match i {");
        foreach (EnumMember member in members)
        {
            long v = Convert.ToInt64(member.Value);
            if (v < int.MinValue || v > int.MaxValue)
            {
                _logger.LogWarning(
                    LogCategory.Fixme,
                    $"Enum {enumRustName} member {member.Name} value {v} is outside i32; skipping from_i32 arm.");
                continue;
            }

            int arm = (int)v;
            _w.Line($"    {arm} => Self::{member.Name.HumanizeVariant()},");
        }

        _w.Line("    _ => {");
        _w.Line(
            $"        warn!(\"invalid {enumRustName} discriminant {{}}; using default\", i);");
        _w.Line($"        Self::{defaultVariant}");
        _w.Line("    }");
        _w.Line("}");
    }

    /// <summary>Rust pattern literal matching <paramref name="rustType"/> (underlying storage).</summary>
    private static string FormatRustPatternLiteralForUnderlying(object value, string rustType)
    {
        return rustType switch
        {
            "u8" => Convert.ToByte(value).ToString(),
            "i8" => Convert.ToSByte(value).ToString(),
            "u16" => $"{Convert.ToUInt16(value)}u16",
            "i16" => $"{Convert.ToInt16(value)}",
            "u32" => $"{Convert.ToUInt32(value)}u32",
            "i32" => $"{Convert.ToInt32(value)}",
            "u64" => $"{Convert.ToUInt64(value)}u64",
            "i64" => $"{Convert.ToInt64(value)}i64",
            _ => Convert.ToInt64(value).ToString(),
        };
    }

    // ── Flags Enum ───────────────────────────────────────────────

    private void EmitFlagsEnum(TypeDescriptor type)
    {
        if (type.EnumMembers == null || type.RustUnderlyingType == null)
        {
            _logger.LogWarning(
                LogCategory.Fixme,
                $"Skipping flags enum {type.CSharpName}: missing EnumMembers or RustUnderlyingType in IR.");
            return;
        }

        string rustType = type.RustUnderlyingType;
        string name = type.RustName;

        // repr(transparent) struct
        _w.TransparentStruct(name, rustType);

        _w.BlankLine();
        using (_w.BeginImpl(name))
        {
            foreach (EnumMember member in type.EnumMembers)
            {
                int val = Convert.ToInt32(member.Value);
                if (val == 0) continue;
                string constName = member.Name.HumanizeField().ToUpperInvariant();
                _w.Line($"pub const {constName}: {rustType} = {val};");
            }
            foreach (EnumMember member in type.EnumMembers)
            {
                int val = Convert.ToInt32(member.Value);
                if (val == 0) continue;
                string methodName = member.Name.HumanizeField();
                string constName = member.Name.HumanizeField().ToUpperInvariant();
                _w.Line($"pub fn {methodName}(&self) -> bool {{ self.0 & Self::{constName} != 0 }}");
            }
        }

        // MemoryPackable impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                _w.Line("packer.write(&self.0);");
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                _w.Line("self.0 = unpacker.read();");
        }
    }

    // ── Pod Struct (ExplicitLayout) ──────────────────────────────

    private void EmitPodStruct(TypeDescriptor type)
    {
        string name = type.RustName;

        // Emit fields in offset order for ExplicitLayout so repr(C) matches C# layout
        var orderedFields = type.Fields
            .OrderBy(f => f.ExplicitOffset ?? int.MaxValue)
            .ToList();

        // Padding may be in orderedFields (synthetic _padding at correct offsets) or trailing
        bool hasPaddingFields = orderedFields.Any(f => f.RustName.StartsWith("_padding"));
        bool needsTrailingPadding = type.PaddingBytes > 0 && !hasPaddingFields;

        // Struct definition (Clone needed when used in Option/Vec)
        if (type.IsPod)
        {
            using (_w.BeginExternStruct(name, "Clone", "Copy", "Pod", "Zeroable"))
            {
                foreach (FieldDescriptor field in orderedFields)
                    _w.StructMember(field.RustName, field.RustType);
                if (needsTrailingPadding)
                    _w.StructMember("_padding", $"[u8; {type.PaddingBytes}]");
            }
        }
        else
        {
            using (_w.BeginExternStruct(name, "Clone", "Copy"))
            {
                foreach (FieldDescriptor field in orderedFields)
                    _w.StructMember(field.RustName, field.RustType);
                if (needsTrailingPadding)
                    _w.StructMember("_padding", $"[u8; {type.PaddingBytes}]");
            }
        }

        if (type.HostInteropSizeBytes is int hostBytes)
        {
            string prefix = type.RustName.ToScreamingSnakeTypeName();
            _w.DocLine($"Host interop size from C# `Marshal.SizeOf` for `{type.CSharpName}` (SHM row stride).");
            _w.Line($"pub const {prefix}_HOST_ROW_BYTES: usize = {hostBytes};");
            _w.BlankLine();
        }

        // MemoryPackable impl (use same field order as struct for correct wire format)
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                PackEmitter.EmitExplicitPack(_w, _logger, type.CSharpName, orderedFields, needsTrailingPadding ? type.PaddingBytes : 0);
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                PackEmitter.EmitExplicitUnpack(_w, _logger, type.CSharpName, orderedFields, needsTrailingPadding ? type.PaddingBytes : 0);
        }

        if (!type.IsPod && type.HostInteropSizeBytes.HasValue)
        {
            string prefix = type.RustName.ToScreamingSnakeTypeName();
            string testFn = $"verify_{type.RustName.HumanizeField()}_host_row_bytes_contract";
            _w.BlankLine();
            _w.Line("#[cfg(test)]");
            _w.Line("#[test]");
            _w.Line($"fn {testFn}() {{");
            _w.Indent();
            _w.Line($"let mut buf = vec![0u8; {prefix}_HOST_ROW_BYTES];");
            _w.Line("let mut packer = MemoryPacker::new(&mut buf);");
            _w.Line($"let mut v = {name}::default();");
            _w.Line("v.pack(&mut packer);");
            _w.Line("assert_eq!(packer.remaining_len(), 0, \"pack must fill host row\");");
            _w.Dedent();
            _w.Line("}");
        }
    }

    // ── Packable Struct (IMemoryPackable) ────────────────────────

    private void EmitPackableStruct(TypeDescriptor type)
    {
        string name = type.RustName;

        // Struct definition (Clone needed when used in Option/Vec)
        using (_w.BeginStruct(name, "Clone"))
        {
            foreach (FieldDescriptor field in type.Fields)
                _w.StructMember(field.RustName, field.RustType);
        }

        // MemoryPackable impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                PackEmitter.EmitPack(_w, _logger, type.CSharpName, type.PackSteps, type.Fields);
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                PackEmitter.EmitUnpack(_w, _logger, type.CSharpName, type.PackSteps, type.Fields, type.UnpackOnlySteps);
        }
    }

    // ── General Struct (e.g., Guid) ──────────────────────────────

    private void EmitGeneralStruct(TypeDescriptor type)
    {
        string name = type.RustName;

        if (type.IsPod)
        {
            using (_w.BeginExternStruct(name, "Clone", "Copy", "Pod", "Zeroable"))
            {
                foreach (FieldDescriptor field in type.Fields)
                    _w.StructMember(field.RustName, field.RustType);
            }
        }
        else
        {
            using (_w.BeginExternStruct(name))
            {
                foreach (FieldDescriptor field in type.Fields)
                    _w.StructMember(field.RustName, field.RustType);
            }
        }

        // Only emit MemoryPackable if the type has pack steps (e.g., Guid)
        if (type.PackSteps.Count > 0)
        {
            _w.BlankLine();
            using (_w.BeginTraitImpl("MemoryPackable", name))
            {
                using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                    PackEmitter.EmitPack(_w, _logger, type.CSharpName, type.PackSteps, type.Fields);
                using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                    PackEmitter.EmitUnpack(_w, _logger, type.CSharpName, type.PackSteps, type.Fields, type.UnpackOnlySteps);
            }
        }
    }

    // ── Roundtrip dispatch (for C#–Rust serialization tests) ───────

    private void EmitRoundtripDispatch(List<TypeDescriptor> types)
    {
        var roundtripable = types.Where(t =>
            (t.Shape == TypeShape.PackableStruct || t.Shape == TypeShape.GeneralStruct)
            && (t.PackSteps.Count > 0 || t.Shape == TypeShape.PackableStruct)
            && !t.RustName.Contains('<')).ToList();

        if (roundtripable.Count == 0) return;

        _w.BlankLine();
        _w.Comment("Roundtrip dispatch for C#–Rust serialization tests. Called by the roundtrip binary.");
        using (_w.BeginMethod("roundtrip_dispatch", "std::io::Result<Vec<u8>>", null, ["type_name: &str", "input: &[u8]"], isPublic: true))
        {
            _w.Line("use super::packing::default_entity_pool::DefaultEntityPool;");
            _w.Line("let mut pool = DefaultEntityPool;");
            _w.Line("let mut unpacker = MemoryUnpacker::new(input, &mut pool);");
            _w.Line("let mut output = vec![0u8; 1024 * 1024];");
            _w.Line("let original_len = output.len();");
            _w.Line("let mut packer = MemoryPacker::new(&mut output[..]);");
            _w.BlankLine();
            _w.Line("match type_name {");
            foreach (var t in roundtripable)
            {
                string rustName = t.RustName;
                _w.Line($"    \"{t.CSharpName}\" => {{ let mut x = {rustName}::default(); x.unpack(&mut unpacker); x.pack(&mut packer); }}");
            }
            _w.Line("    _ => return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, format!(\"Unknown type: {}\", type_name))),");
            _w.Line("}");
            _w.BlankLine();
            _w.Line("let written = original_len - packer.remaining_len();");
            _w.Line("output.truncate(written);");
            _w.Line("Ok(output)");
        }
    }
}
