// --- Material block (UnityShaderConverter) @group(2) ---
struct MaterialUniform {
    color: vec4<f32>,
    cutoff: f32,
    srcBlend: f32,
    dstBlend: f32,
    zWrite: f32,
    cull: f32,
    _pad0: u32,
    _pad1: u32,
    _pad2: u32,
    offsetMagnitude: vec4<f32>,
    polarPow: f32,
    zTest: f32,
    _pad3: u32,
    _pad4: u32,
}

@group(2) @binding(0) var<uniform> material: MaterialUniform;
@group(2) @binding(1) var tex: texture_2d<f32>;
@group(2) @binding(2) var tex_sampler: sampler;
@group(2) @binding(3) var offsetTex: texture_2d<f32>;
@group(2) @binding(4) var offsetTex_sampler: sampler;
@group(2) @binding(5) var maskTex: texture_2d<f32>;
@group(2) @binding(6) var maskTex_sampler: sampler;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(11) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(9) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
fn UnityObjectToClipPos_0( pos_0 : vec3<f32>) -> vec4<f32>
{
    return ((((((vec4<f32>(pos_0, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityObjectToClipPos_1( pos_1 : vec4<f32>) -> vec4<f32>
{
    return UnityObjectToClipPos_0(pos_1.xyz);
}

struct v2f_0
{
    @builtin(position) vertex_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) vertex_1 : vec4<f32>,
};

@vertex
fn vert( _S1 : vertexInput_0) -> v2f_0
{
    var o_0 : v2f_0;
    o_0.vertex_0 = UnityObjectToClipPos_1(_S1.vertex_1);
    return o_0;
}



struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

@fragment
fn frag(@builtin(position) vertex_0 : vec4<f32>) -> pixelOutput_0
{
    var _S1 : pixelOutput_0 = pixelOutput_0( vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f) );
    return _S1;
}

