using System.Globalization;
using System.Text;
using UnityShaderConverter.Analysis;
using UnityShaderParser.ShaderLab;

namespace UnityShaderConverter.Emission;

/// <summary>Emits bundled Rust modules for WGSL <c>include_str!</c> paths and material descriptors.</summary>
public static class RustEmitter
{
    /// <summary>Sanitized Rust module name (snake_case).</summary>
    public static string ModuleNameFromShaderName(string shaderName) => ShaderNaming.ModuleName(shaderName);

    /// <summary>WGSL artifact file name (no directory).</summary>
    public static string WgslFileName(string shaderName, int passIndex, int variantIndex) =>
        $"{ShaderNaming.FileStem(shaderName)}_pass{passIndex}_v{variantIndex}.wgsl";

    /// <summary>Slang artifact file name (no directory) — used only for logging when needed.</summary>
    public static string SlangFileName(string shaderName, int passIndex, int variantIndex) =>
        $"{ShaderNaming.FileStem(shaderName)}_pass{passIndex}_v{variantIndex}.slang";

    /// <summary>Stable Rust constant name for one pass×variant WGSL blob.</summary>
    public static string WgslConstName(int passIndex, int variantIndex) => $"PASS{passIndex}_V{variantIndex}";

    /// <summary>Full contents of <c>wgsl_sources.rs</c> for all successful shaders.</summary>
    public static string EmitWgslSourcesFile(
        IReadOnlyList<(string ModName, ShaderFileDocument Document, string SourceComment, IReadOnlyList<(int PassIndex, int VariantIndex, string WgslRelativePath)> Artifacts)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.AppendLine("//! WGSL sources as `include_str!` (nested paths under `wgsl/`).");
        sb.AppendLine();
        foreach (var e in entries)
            AppendWgslSubmodule(sb, e.ModName, e.Document, e.SourceComment, e.Artifacts);
        return sb.ToString();
    }

    /// <summary>Full contents of <c>materials.rs</c> for all successful shaders.</summary>
    public static string EmitMaterialsFile(
        IReadOnlyList<(string ModName, ShaderFileDocument Document, string SourceComment)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//! @generated by UnityShaderConverter — do not edit.");
        sb.AppendLine("//! Material structs and wgpu helpers derived from Unity ShaderLab Properties.");
        sb.AppendLine();
        foreach (var e in entries)
            AppendMaterialsSubmodule(sb, e.ModName, e.Document, e.SourceComment);
        return sb.ToString();
    }

    /// <summary>Appends one <c>pub mod</c> with WGSL string constants.</summary>
    public static void AppendWgslSubmodule(
        StringBuilder sb,
        string modName,
        ShaderFileDocument document,
        string sourcePathForComment,
        IReadOnlyList<(int PassIndex, int VariantIndex, string WgslRelativePath)> wgslArtifacts)
    {
        sb.Append("/// Unity shader: `").Append(document.ShaderName).AppendLine("`");
        sb.Append("/// Source: `").Append(sourcePathForComment.Replace("\\", "/")).AppendLine("`");
        sb.Append("pub mod ").Append(modName).AppendLine(" {");
        foreach ((int passIndex, int variantIndex, string rel) in wgslArtifacts)
        {
            string constName = WgslConstName(passIndex, variantIndex);
            sb.Append("    /// WGSL for pass ").Append(passIndex).Append(", variant ").Append(variantIndex).AppendLine(".");
            sb.Append("    pub const ").Append(constName).Append(": &str = include_str!(\"");
            sb.Append(rel.Replace("\\", "/"));
            sb.AppendLine("\");");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>Appends one <c>pub mod</c> with <c>Material</c>, defaults, and pipeline helpers.</summary>
    public static void AppendMaterialsSubmodule(
        StringBuilder sb,
        string modName,
        ShaderFileDocument document,
        string sourcePathForComment)
    {
        sb.Append("/// Unity shader: `").Append(document.ShaderName).AppendLine("`");
        sb.Append("/// Source: `").Append(sourcePathForComment.Replace("\\", "/")).AppendLine("`");
        sb.Append("pub mod ").Append(modName).AppendLine(" {");
        sb.AppendLine("    use glam::Vec4;");
        sb.AppendLine();
        sb.AppendLine("    /// Default material values mapped from the Unity Properties block.");
        sb.AppendLine("    pub struct Material {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            sb.Append("        pub ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(RustPropertyType(prop)).Append(", // ")
                .AppendLine(EscapeComment(prop.DisplayLabel));
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    impl Default for Material {");
        sb.AppendLine("        fn default() -> Self {");
        sb.AppendLine("            Self {");
        foreach (ShaderPropertyRecord prop in document.Properties)
        {
            sb.Append("                ").Append(RustFieldName(prop.Name)).Append(": ")
                .Append(DefaultRustValue(prop)).AppendLine(",");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// Placeholder bind group layout entries for material uniforms (group 1) — extend as WGSL bindings are added.");
        sb.AppendLine("    pub fn material_bind_group_layout_entries() -> &'static [wgpu::BindGroupLayoutEntry] {");
        sb.AppendLine("        &[]");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// Creates an empty material bind group layout (until textures/uniforms are wired).");
        sb.AppendLine("    pub fn create_material_bind_group_layout(device: &wgpu::Device, label: &str) -> wgpu::BindGroupLayout {");
        sb.AppendLine("        device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {");
        sb.AppendLine("            label: Some(label),");
        sb.AppendLine("            entries: material_bind_group_layout_entries(),");
        sb.AppendLine("        })");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// Single color attachment state for the given surface format.");
        sb.AppendLine("    pub fn color_target_state(format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {");
        sb.AppendLine("        Some(wgpu::ColorTargetState {");
        sb.AppendLine("            format,");
        sb.AppendLine("            blend: None,");
        sb.AppendLine("            write_mask: wgpu::ColorWrites::ALL,");
        sb.AppendLine("        })");
        sb.AppendLine("    }");
        sb.AppendLine();
        if (document.Passes.Count > 0)
        {
            sb.AppendLine("    /// Vertex shader entry name produced by Slang for this shader (pass 0).");
            sb.Append("    pub const VERTEX_ENTRY_PASS0: &str = \"");
            sb.Append(EscapeRustString(document.Passes[0].VertexEntry!)).AppendLine("\";");
            sb.Append("    pub const FRAGMENT_ENTRY_PASS0: &str = \"");
            sb.Append(EscapeRustString(document.Passes[0].FragmentEntry!)).AppendLine("\";");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string EscapeRustString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string RustFieldName(string uniformName)
    {
        string n = uniformName.TrimStart('_');
        if (n.Length == 0)
            n = "unnamed";
        string lowered = $"{char.ToLowerInvariant(n[0])}{n.AsSpan(1)}";
        return RustEscapeIdent(lowered);
    }

    private static string RustEscapeIdent(string s)
    {
        if (s.Length > 0 && char.IsDigit(s[0]))
            return "u_" + s;
        return s;
    }

    private static string RustPropertyType(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range => "f32",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int => "i32",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector => "Vec4",
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "u32",
            _ => "()",
        };

    private static string DefaultRustValue(ShaderPropertyRecord prop) =>
        prop.Kind switch
        {
            ShaderPropertyKind.Float or ShaderPropertyKind.Range =>
                prop.DefaultSummary.Length > 0 && float.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out float f)
                    ? f.ToString(CultureInfo.InvariantCulture)
                    : "0.0",
            ShaderPropertyKind.Integer or ShaderPropertyKind.Int =>
                prop.DefaultSummary.Length > 0 && int.TryParse(prop.DefaultSummary, CultureInfo.InvariantCulture, out int i)
                    ? i.ToString(CultureInfo.InvariantCulture)
                    : "0",
            ShaderPropertyKind.Color or ShaderPropertyKind.Vector =>
                ParseVec4Default(prop.DefaultSummary),
            ShaderPropertyKind.Texture2D or ShaderPropertyKind.Texture3D or ShaderPropertyKind.TextureCube
                or ShaderPropertyKind.TextureAny or ShaderPropertyKind.Texture2DArray
                or ShaderPropertyKind.Texture3DArray or ShaderPropertyKind.TextureCubeArray => "0",
            _ => "()",
        };

    private static string ParseVec4Default(string summary)
    {
        ReadOnlySpan<char> s = summary.AsSpan().Trim();
        if (s.Length < 5 || s[0] != '(')
            return "Vec4::ONE";
        s = s[1..^1];
        var parts = new List<float>();
        foreach (string part in s.ToString().Split(','))
        {
            if (float.TryParse(part.Trim(), CultureInfo.InvariantCulture, out float v))
                parts.Add(v);
        }

        if (parts.Count >= 4)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, {F32Lit(parts[3])})";
        if (parts.Count == 3)
            return $"Vec4::new({F32Lit(parts[0])}, {F32Lit(parts[1])}, {F32Lit(parts[2])}, 1.0)";
        return "Vec4::ONE";
    }

    private static string F32Lit(float x)
    {
        string s = x.ToString("G9", CultureInfo.InvariantCulture);
        if (!s.Contains('.') && !s.Contains('E') && !s.Contains('e'))
            s += ".0";
        return s;
    }

    private static string EscapeComment(string s) => s.Replace("*/", "* /");
}
