// Generated by UnityShaderConverter — merged vertex + fragment stages.
enable f16;

struct _MatrixStorage_float4x4_ColMajorstd140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct SLANG_ParameterGroup_UnityPerFrame_std140_0
{
    @align(16) glstate_lightmodel_ambient_0 : vec4<f16>,
    @align(8) unity_AmbientSky_0 : vec4<f16>,
    @align(16) unity_AmbientEquator_0 : vec4<f16>,
    @align(8) unity_AmbientGround_0 : vec4<f16>,
    @align(16) unity_IndirectSpecColor_0 : vec4<f16>,
    @align(16) glstate_matrix_projection_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixInvV_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_MatrixVP_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_StereoEyeIndex_0 : i32,
    @align(8) unity_ShadowColor_0 : vec4<f16>,
};

@binding(9) @group(0) var<uniform> UnityPerFrame_0 : SLANG_ParameterGroup_UnityPerFrame_std140_0;
struct SLANG_ParameterGroup_UnityPerDraw_std140_0
{
    @align(16) unity_ObjectToWorld_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_WorldToObject_0 : _MatrixStorage_float4x4_ColMajorstd140_0,
    @align(16) unity_LODFade_0 : vec4<f32>,
    @align(16) unity_WorldTransformParams_0 : vec4<f32>,
    @align(16) unity_RenderingLayer_0 : vec4<f32>,
};

@binding(7) @group(0) var<uniform> UnityPerDraw_0 : SLANG_ParameterGroup_UnityPerDraw_std140_0;
fn UnityObjectToClipPos_0( pos_0 : vec3<f32>) -> vec4<f32>
{
    return ((((((vec4<f32>(pos_0, 1.0f)) * (mat4x4<f32>(UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(0)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(1)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(2)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(0)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(1)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(2)][i32(3)], UnityPerDraw_0.unity_ObjectToWorld_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(0)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(1)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(2)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(0)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(1)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(2)][i32(3)], UnityPerFrame_0.unity_MatrixVP_0.data_0[i32(3)][i32(3)]))));
}

fn UnityObjectToClipPos_1( pos_1 : vec4<f32>) -> vec4<f32>
{
    return UnityObjectToClipPos_0(pos_1.xyz);
}

struct v2f_0
{
    @builtin(position) vertex_0 : vec4<f32>,
    @location(0) checker_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) vertex_1 : vec4<f32>,
};

@vertex
fn vert( _S1 : vertexInput_0) -> v2f_0
{
    var o_0 : v2f_0;
    o_0.checker_0 = _S1.vertex_1.xyz * vec3<f32>(5.0f);
    o_0.vertex_0 = UnityObjectToClipPos_1(_S1.vertex_1);
    return o_0;
}



enable f16;

fn transition_0( p_0 : f32,  a_0 : ptr<function, f32>,  b_0 : ptr<function, f32>)
{
    var _S1 : f32 = p_0 * 50.0f;
    var _S2 : f32;
    if(_S1 < 12.5f)
    {
        _S2 = saturate(_S1 + 0.5f);
    }
    else
    {
        if(_S1 < 37.5f)
        {
            _S2 = 1.0f - saturate(_S1 - 25.0f - 0.5f);
        }
        else
        {
            _S2 = 1.0f - saturate(50.0f - _S1 + 0.5f);
        }
    }
    var _b_0 : f32 = mix((*b_0), (*a_0), _S2);
    (*a_0) = mix((*a_0), (*b_0), _S2);
    (*b_0) = _b_0;
    return;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f16>,
};

struct pixelInput_0
{
    @location(0) checker_0 : vec3<f32>,
};

struct v2f_0
{
     vertex_0 : vec4<f32>,
     checker_1 : vec3<f32>,
};

@fragment
fn frag( _S3 : pixelInput_0, @builtin(position) vertex_1 : vec4<f32>) -> pixelOutput_0
{
    var _S4 : v2f_0;
    _S4.vertex_0 = vertex_1;
    _S4.checker_1 = _S3.checker_0;
    var _S5 : vec3<f32> = fract(_S4.checker_1);
    _S4.checker_1 = _S5;
    var a_1 : f32 = 0.0f;
    var b_1 : f32 = 0.05000000074505806f;
    transition_0(_S5.x, &(a_1), &(b_1));
    transition_0(_S5.y, &(a_1), &(b_1));
    transition_0(_S5.z, &(a_1), &(b_1));
    var _S6 : pixelOutput_0 = pixelOutput_0( vec4<f16>(vec3<f16>(vec3<f32>(a_1)), 1.0h) );
    return _S6;
}

