using SharedTypeGenerator.Analysis;
using SharedTypeGenerator.IR;

namespace SharedTypeGenerator.Emission;

/// <summary>Backend orchestrator: takes a list of TypeDescriptors and emits the complete
/// shared.rs file. Dispatches each type to shape-specific emission methods.
/// No reflection, no Cecil -- purely data-driven from the IR.</summary>
public class RustEmitter
{
    private readonly RustWriter _w;
    private readonly string _engineVersion;

    public RustEmitter(RustWriter writer, string engineVersion)
    {
        _w = writer;
        _engineVersion = engineVersion;
    }

    /// <summary>Emits the complete shared.rs file from the analyzed type list.</summary>
    public void Emit(List<TypeDescriptor> types)
    {
        EmitHeader();

        foreach (TypeDescriptor type in types)
        {
            EmitType(type);
            _w.BlankLine();
        }

        EmitRoundtripDispatch(types);
    }

    private void EmitHeader()
    {
        _w.Comment("This file is automatically generated by SharedTypeGenerator. Please do not modify this file.");
        _w.Comment($"Generated for {_engineVersion}\n");
        _w.Line("#![allow(non_camel_case_types, non_snake_case, clippy::missing_transmute_annotations, clippy::unnecessary_cast, clippy::unused_parens, clippy::large_enum_variant)]");
        _w.BlankLine();
        _w.Line("use nalgebra::{Vector2, Vector3, Vector4, Quaternion, Matrix4};");
        _w.Line("use super::memory_packable::MemoryPackable;");
        _w.Line("use super::memory_packer::MemoryPacker;");
        _w.Line("use super::memory_unpacker::MemoryUnpacker;");
        _w.Line("use super::memory_packer_entity_pool::MemoryPackerEntityPool;");
        _w.Line("use super::polymorphic_memory_packable_entity::PolymorphicEncode;");
        _w.Line("use super::buffer::SharedMemoryBufferDescriptor;");
        _w.Line("use super::enum_repr::EnumRepr;");
        _w.Line("use bytemuck::{Pod, Zeroable};");
        _w.BlankLine();
    }

    private void EmitType(TypeDescriptor type)
    {
        switch (type.Shape)
        {
            case TypeShape.PolymorphicBase:
                EmitPolymorphic(type);
                break;
            case TypeShape.ValueEnum:
                EmitValueEnum(type);
                break;
            case TypeShape.FlagsEnum:
                EmitFlagsEnum(type);
                break;
            case TypeShape.PodStruct:
                EmitPodStruct(type);
                break;
            case TypeShape.PackableStruct:
                EmitPackableStruct(type);
                break;
            case TypeShape.GeneralStruct:
                EmitGeneralStruct(type);
                break;
        }
    }

    // ── Polymorphic ──────────────────────────────────────────────

    private void EmitPolymorphic(TypeDescriptor type)
    {
        if (type.Variants == null || type.Variants.Count == 0) return;

        string unionName = type.RustName;
        var typeNames = type.Variants.Select(v => v.CSharpName).ToList();

        // Discriminant enum: {Name}Types
        using (_w.BeginEnum($"{type.CSharpName}Types", "i32"))
        {
            bool first = true;
            foreach (string name in typeNames)
            {
                _w.EnumMember(name, isDefault: first);
                first = false;
            }
        }

        // Tagged union enum (Clone needed when used in Option/Vec; no Default - variants have payloads)
        using (_w.BeginUnion(type.CSharpName, "Clone"))
        {
            foreach (string name in typeNames)
                _w.EnumVariantWithPayload(name, name);
        }

        // PolymorphicEncode impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("PolymorphicEncode", unionName))
        {
            using (_w.BeginMethod("encode", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
            {
                _w.Line("match self {");
                for (int i = 0; i < typeNames.Count; i++)
                {
                    string variant = typeNames[i].HumanizeField();
                    _w.Line($"    {unionName}::{variant}(x) => {{ packer.write(&{i}i32); x.pack(packer); }}");
                }
                _w.Line("}");
            }
        }

        // decode function
        string decodeFnName = "decode_" + unionName.HumanizeField();
        _w.BlankLine();
        using (_w.BeginMethod(decodeFnName, unionName, ["P: MemoryPackerEntityPool"], ["unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: true))
        {
            _w.Line("let tag = unpacker.read::<i32>();");
            _w.Line("match tag {");
            for (int i = 0; i < typeNames.Count; i++)
            {
                string variant = typeNames[i].HumanizeField();
                string payloadType = typeNames[i].HumanizeType();
                _w.Line($"    {i} => {unionName}::{variant}({{ let mut x = {payloadType}::default(); x.unpack(unpacker); x }}),");
            }
            _w.Line("    _ => panic!(\"Invalid polymorphic tag: {:?}\", tag),");
            _w.Line("}");
        }
    }

    // ── Value Enum ───────────────────────────────────────────────

    private void EmitValueEnum(TypeDescriptor type)
    {
        if (type.EnumMembers == null || type.RustUnderlyingType == null) return;

        string rustType = type.RustUnderlyingType;
        string name = type.RustName;

        // Enums used as keys or in comparisons need PartialEq
        using (_w.BeginEnum(name, rustType, "PartialEq"))
        {
            foreach (EnumMember member in type.EnumMembers)
                _w.EnumMemberWithValue(member.Name, member.Value.ToString()!, isDefault: member.IsDefault);
        }

        // MemoryPackable impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                _w.Line($"packer.write(&(*self as {rustType}));");
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                _w.Line($"unsafe {{ std::ptr::write(self as *mut Self, std::mem::transmute::<{rustType}, Self>(unpacker.read::<{rustType}>())) }};");
        }

        // EnumRepr impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("EnumRepr", name))
        {
            using (_w.BeginMethod("as_i32", "i32", null, ["self"], isPublic: false))
                _w.Line("self as i32");
            using (_w.BeginMethod("from_i32", "Self", null, ["i: i32"], isPublic: false))
            {
                string castExpr = rustType == "i32" ? "i" : $"i as {rustType}";
                _w.Line($"unsafe {{ std::mem::transmute::<{rustType}, Self>({castExpr}) }}");
            }
        }

        _w.BlankLine();
        _w.Line($"unsafe impl Pod for {name} {{}}");
        _w.Line($"unsafe impl Zeroable for {name} {{}}");
    }

    // ── Flags Enum ───────────────────────────────────────────────

    private void EmitFlagsEnum(TypeDescriptor type)
    {
        if (type.EnumMembers == null || type.RustUnderlyingType == null) return;

        string rustType = type.RustUnderlyingType;
        string name = type.RustName;

        // repr(transparent) struct
        _w.TransparentStruct(name, rustType);

        _w.BlankLine();
        using (_w.BeginImpl(name))
        {
            foreach (EnumMember member in type.EnumMembers)
            {
                int val = Convert.ToInt32(member.Value);
                if (val == 0) continue;
                string constName = member.Name.HumanizeField().ToUpperInvariant();
                _w.Line($"pub const {constName}: {rustType} = {val};");
            }
            foreach (EnumMember member in type.EnumMembers)
            {
                int val = Convert.ToInt32(member.Value);
                if (val == 0) continue;
                string methodName = member.Name.HumanizeField();
                string constName = member.Name.HumanizeField().ToUpperInvariant();
                _w.Line($"pub fn {methodName}(&self) -> bool {{ self.0 & Self::{constName} != 0 }}");
            }
        }

        // MemoryPackable impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                _w.Line("packer.write(&self.0);");
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                _w.Line("self.0 = unpacker.read();");
        }
    }

    // ── Pod Struct (ExplicitLayout) ──────────────────────────────

    private void EmitPodStruct(TypeDescriptor type)
    {
        string name = type.RustName;

        // Emit fields in offset order for ExplicitLayout so repr(C) matches C# layout
        var orderedFields = type.Fields
            .OrderBy(f => f.ExplicitOffset ?? int.MaxValue)
            .ToList();

        // Padding may be in orderedFields (synthetic _padding at correct offsets) or trailing
        bool hasPaddingFields = orderedFields.Any(f => f.RustName.StartsWith("_padding"));
        bool needsTrailingPadding = type.PaddingBytes > 0 && !hasPaddingFields;

        // Struct definition (Clone needed when used in Option/Vec)
        if (type.IsPod)
        {
            using (_w.BeginExternStruct(name, "Clone", "Copy", "Pod", "Zeroable"))
            {
                foreach (FieldDescriptor field in orderedFields)
                    _w.StructMember(field.RustName, field.RustType);
                if (needsTrailingPadding)
                    _w.StructMember("_padding", $"[u8; {type.PaddingBytes}]");
            }
        }
        else
        {
            using (_w.BeginExternStruct(name, "Clone"))
            {
                foreach (FieldDescriptor field in orderedFields)
                    _w.StructMember(field.RustName, field.RustType);
                if (needsTrailingPadding)
                    _w.StructMember("_padding", $"[u8; {type.PaddingBytes}]");
            }
        }

        // MemoryPackable impl (use same field order as struct for correct wire format)
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                PackEmitter.EmitExplicitPack(_w, orderedFields, needsTrailingPadding ? type.PaddingBytes : 0);
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                PackEmitter.EmitExplicitUnpack(_w, orderedFields, needsTrailingPadding ? type.PaddingBytes : 0);
        }
    }

    // ── Packable Struct (IMemoryPackable) ────────────────────────

    private void EmitPackableStruct(TypeDescriptor type)
    {
        string name = type.RustName;

        // Struct definition (Clone needed when used in Option/Vec)
        using (_w.BeginStruct(name, "Clone"))
        {
            foreach (FieldDescriptor field in type.Fields)
                _w.StructMember(field.RustName, field.RustType);
        }

        // MemoryPackable impl
        _w.BlankLine();
        using (_w.BeginTraitImpl("MemoryPackable", name))
        {
            using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                PackEmitter.EmitPack(_w, type.PackSteps, type.Fields);
            using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                PackEmitter.EmitUnpack(_w, type.PackSteps, type.Fields, type.UnpackOnlySteps);
        }
    }

    // ── General Struct (e.g., Guid) ──────────────────────────────

    private void EmitGeneralStruct(TypeDescriptor type)
    {
        string name = type.RustName;

        if (type.IsPod)
        {
            using (_w.BeginExternStruct(name, "Clone", "Copy", "Pod", "Zeroable"))
            {
                foreach (FieldDescriptor field in type.Fields)
                    _w.StructMember(field.RustName, field.RustType);
            }
        }
        else
        {
            using (_w.BeginExternStruct(name))
            {
                foreach (FieldDescriptor field in type.Fields)
                    _w.StructMember(field.RustName, field.RustType);
            }
        }

        // Only emit MemoryPackable if the type has pack steps (e.g., Guid)
        if (type.PackSteps.Count > 0)
        {
            _w.BlankLine();
            using (_w.BeginTraitImpl("MemoryPackable", name))
            {
                using (_w.BeginMethod("pack", "", null, ["&mut self", "packer: &mut MemoryPacker<'_>"], isPublic: false))
                    PackEmitter.EmitPack(_w, type.PackSteps, type.Fields);
                using (_w.BeginMethod("unpack", "", ["P: MemoryPackerEntityPool"], ["&mut self", "unpacker: &mut MemoryUnpacker<'_, '_, P>"], isPublic: false))
                    PackEmitter.EmitUnpack(_w, type.PackSteps, type.Fields, type.UnpackOnlySteps);
            }
        }
    }

    // ── Roundtrip dispatch (for C#–Rust serialization tests) ───────

    private void EmitRoundtripDispatch(List<TypeDescriptor> types)
    {
        var roundtripable = types.Where(t =>
            (t.Shape == TypeShape.PackableStruct || t.Shape == TypeShape.GeneralStruct)
            && (t.PackSteps.Count > 0 || t.Shape == TypeShape.PackableStruct)
            && !t.RustName.Contains('<')).ToList();

        if (roundtripable.Count == 0) return;

        _w.BlankLine();
        _w.Comment("Roundtrip dispatch for C#–Rust serialization tests. Called by the roundtrip binary.");
        using (_w.BeginMethod("roundtrip_dispatch", "std::io::Result<Vec<u8>>", null, ["type_name: &str", "input: &[u8]"], isPublic: true))
        {
            _w.Line("use super::default_entity_pool::DefaultEntityPool;");
            _w.Line("let mut pool = DefaultEntityPool;");
            _w.Line("let mut unpacker = MemoryUnpacker::new(input, &mut pool);");
            _w.Line("let mut output = vec![0u8; 1024 * 1024];");
            _w.Line("let original_len = output.len();");
            _w.Line("let mut packer = MemoryPacker::new(&mut output[..]);");
            _w.BlankLine();
            _w.Line("match type_name {");
            foreach (var t in roundtripable)
            {
                string rustName = t.RustName;
                _w.Line($"    \"{t.CSharpName}\" => {{ let mut x = {rustName}::default(); x.unpack(&mut unpacker); x.pack(&mut packer); }}");
            }
            _w.Line("    _ => return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, format!(\"Unknown type: {}\", type_name))),");
            _w.Line("}");
            _w.BlankLine();
            _w.Line("let written = original_len - packer.remaining_len();");
            _w.Line("output.truncate(written);");
            _w.Line("Ok(output)");
        }
    }
}
