//! @generated by UnityShaderConverter — do not edit.
//! Unity shader: `Converter/MinimalUnlit`
//! Source: `generators/UnityShaderConverter/SampleShaders/MinimalUnlit.shader`
//! One WGSL file per pass (`passN.wgsl`). Variants use WGSL `override` via `wgpu::PipelineCompilationOptions` when specialization is enabled.

use glam::Vec4;

/// No `multi_compile` specialization axes were extracted; pipeline constants are unused.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct VariantKey;

/// Merged vertex + fragment WGSL for pass 0.
pub const PASS0_WGSL: &str = include_str!("pass0.wgsl");

/// Default material values mapped from the Unity Properties block.
#[derive(Clone, Debug, PartialEq)]
pub struct Material {
    pub color: Vec4, // Color
}

impl Default for Material {
    fn default() -> Self {
        Self {
            color: Vec4::new(1.0, 1.0, 1.0, 1.0),
        }
    }
}

/// WGSL source for use with `Device::create_shader_module`.
pub fn shader_source_pass0() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS0_WGSL.into())
}

/// Defaults until you map `specialization_constants_f64` into a leaked or cached slice for `constants`.
pub fn pipeline_compilation_options_pass0_vertex(
    _variant: &VariantKey,
) -> wgpu::PipelineCompilationOptions<'static> {
    wgpu::PipelineCompilationOptions::default()
}

pub fn pipeline_compilation_options_pass0_fragment(
    variant: &VariantKey,
) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_pass0_vertex(variant)
}

/// Placeholder bind group layout entries for material uniforms (group 1).
pub fn material_bind_group_layout_entries() -> &'static [wgpu::BindGroupLayoutEntry] {
    &[]
}

pub fn create_material_bind_group_layout(
    device: &wgpu::Device,
    label: &str,
) -> wgpu::BindGroupLayout {
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some(label),
        entries: material_bind_group_layout_entries(),
    })
}

pub fn color_target_state(format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
        format,
        blend: None,
        write_mask: wgpu::ColorWrites::ALL,
    })
}

/// Builds a render pipeline using pass 0 WGSL (stub — extend with real layouts and vertex buffers).
pub fn create_render_pipeline_pass0_stub(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    variant: &VariantKey,
) -> wgpu::RenderPipeline {
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("Converter/MinimalUnlit"),
        source: shader_source_pass0(),
    });
    let vertex_opts = pipeline_compilation_options_pass0_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass0_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("vert"),
            buffers: &[],
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })],
            compilation_options: fragment_opts,
        }),
        primitive: wgpu::PrimitiveState::default(),
        depth_stencil: None,
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}
/// Vertex shader entry name produced by Slang for pass 0.
pub const VERTEX_ENTRY_PASS0: &str = "vert";
pub const FRAGMENT_ENTRY_PASS0: &str = "frag";

/// Pass names from ShaderLab (for future pipeline / file naming).
pub const PASS_0_NAME: &str = "pass_0";
