// --- Material block (UnityShaderConverter) @group(2) ---
struct MaterialUniform {
    color: vec4<f32>,
}

@group(2) @binding(0) var<uniform> material: MaterialUniform;
// --- End material block ---

// Generated by UnityShaderConverter — merged vertex + fragment stages.
struct v2f_0
{
    @builtin(position) vertex_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) vertex_1 : vec4<f32>,
};

@vertex
fn vert( _S1 : vertexInput_0) -> v2f_0
{
    var o_0 : v2f_0;
    o_0.vertex_0 = _S1.vertex_1;
    return o_0;
}



struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

@fragment
fn frag(@builtin(position) vertex_0 : vec4<f32>) -> pixelOutput_0
{
    var _S1 : pixelOutput_0 = pixelOutput_0( vec4<f32>(1.0f, 0.0f, 1.0f, 1.0f) );
    return _S1;
}

